/**
 * market-intelligence-ask.ts — Market Intelligence Q&A reasoning layer (Step 2).
 *
 * OpenAI FUNCTION-CALLING (tool-use), not a raw completion prompt. The model
 * may ONLY state facts returned by the four read-only data tools in
 * market-intelligence.ts; it never answers from its own market knowledge.
 *
 * ─── Hard guarantees (enforced in CODE, not just the prompt) ────────────────
 *  1. Tenant scope is bound SERVER-SIDE into the tool executor. The model
 *     never supplies (and cannot override) tenant ids — its tool arguments
 *     are restricted to { role, skills, location }.
 *  2. The source/citation list is built from the ACTUAL tool executions we
 *     ran — never from the model echoing what it claims it called
 *     (interview-recruiter-direction doctrine: don't trust model echo).
 *  3. If ZERO tools returned usable data, the model's narrative is DISCARDED
 *     and replaced with a deterministic insufficient-data answer. No
 *     confident-sounding fabrication can leak through — same test shape as
 *     the fairness "insufficient data" fallback.
 *  4. The confidence/coverage line is computed deterministically from the
 *     executed tool results and always attached — the model can't skip it.
 *  5. Internal-first doctrine: when the internal bench has matches, a
 *     deterministic headline surfaces them at the TOP of the answer and the
 *     bench citation is ordered first, so internal talent is never buried
 *     under external suggestions.
 *
 * Privacy: tool outputs are aggregates (plus internal-bench names the caller
 * already owns in their own tenant pool). No platform-pool personal data and
 * no candidate rows cross tenants through this layer.
 */
import OpenAI from "openai";
import { logger } from "./logger";
import {
  getHiringVelocity,
  getCandidateSupply,
  getCompSignal,
  getInternalBench,
  type ToolResult,
  type InternalBenchOk,
} from "./market-intelligence";

/* ── Result shapes ────────────────────────────────────────────────────────── */

export interface AskSource {
  /** Which data tool produced this citation. */
  tool: MarketToolName;
  /** The exact (sanitized) params the tool ran with. */
  params: { role: string; skills?: string[]; location?: string };
  /** ISO timestamp the tool reported (recency for the UI). */
  asOf: string;
  status: "ok" | "no_data";
  /** Honest sample size backing the figures (undefined on no_data). */
  sampleSize?: number;
  /** One-line human summary of what the tool returned. */
  summary: string;
}

export interface AskCoverage {
  toolsCalled: number;
  okCount: number;
  noDataCount: number;
  /** true only if at least one tool returned real data. */
  sufficient: boolean;
}

/** One row per ATTEMPTED tool call (incl. duplicates + rejected) — audit trail. */
export interface AskExecution {
  round: number;
  tool: string;
  outcome: "ok" | "no_data" | "rejected_unknown_tool" | "rejected_invalid_args" | "execution_failed";
  params?: { role: string; skills?: string[]; location?: string };
  asOf?: string;
  sampleSize?: number;
  summary?: string;
}

export interface AskResult {
  /** Narrative answer (deterministic insufficiency text when nothing had data). */
  answer: string;
  /** Mandatory confidence/coverage line, computed server-side. */
  confidence: string;
  /** Citations from ACTUAL executions, internal bench first when it has data. */
  sources: AskSource[];
  coverage: AskCoverage;
  /** Full audit trail of every attempted tool call (persisted for rollout spot-checks). */
  executions: AskExecution[];
  /**
   * Structured internal-bench matches from the ACTUAL get_internal_bench call
   * (never model-generated) — lets the UI render actionable candidate cards.
   * Present only when the bench tool ran and returned data. Tenant-scoped by
   * the tool itself (caller's own pool), so safe to return to the client.
   */
  benchMatches?: Array<{ candidateId: string; name: string; title: string; matchScore: number; isCurrentEmployee: boolean }>;
  /**
   * GENERAL industry guidance — a structurally SEPARATE, lower-trust channel
   * for thin/zero-data (cold-start) answers. Generated by a second, tool-less
   * model call under GENERAL_GUIDANCE_PROMPT and then passed through
   * scrubGuidanceSpecifics(), which deterministically DROPS any sentence
   * containing a specific figure (salary, %, dollar amount, big number) so
   * the model cannot smuggle fabricated specifics into the "general
   * knowledge" bucket. Directional only; never merged into `answer`.
   * Present only when platform data was thin (okCount <= 1). Best-effort —
   * a failure here never blocks the grounded answer.
   */
  generalGuidance?: string;
}

/* ── Tool registry ────────────────────────────────────────────────────────── */

export type MarketToolName =
  | "get_internal_bench"
  | "get_candidate_supply"
  | "get_hiring_velocity"
  | "get_comp_signal";

const TOOL_ORDER: MarketToolName[] = [
  "get_internal_bench",
  "get_candidate_supply",
  "get_hiring_velocity",
  "get_comp_signal",
];

const COMMON_PARAMS = {
  type: "object" as const,
  properties: {
    role: { type: "string", description: "The role/title being hired for, e.g. 'design engineer'." },
    skills: { type: "array", items: { type: "string" }, description: "Key skills for the role." },
    location: { type: "string", description: "Target location, if the user specified one." },
  },
  required: ["role"],
};

export const MARKET_TOOL_DEFS: OpenAI.Chat.Completions.ChatCompletionTool[] = [
  {
    type: "function",
    function: {
      name: "get_internal_bench",
      description:
        "Check the caller's OWN talent pool for existing matching candidates. FREE answer — always call this FIRST before any external market tool.",
      parameters: COMMON_PARAMS,
    },
  },
  {
    type: "function",
    function: {
      name: "get_candidate_supply",
      description: "Recent qualified-candidate supply from actual sourcing searches for comparable roles (last 30 days).",
      parameters: COMMON_PARAMS,
    },
  },
  {
    type: "function",
    function: {
      name: "get_hiring_velocity",
      description: "Historical days-to-fill statistics and sourced-to-hire ratio for comparable roles.",
      parameters: COMMON_PARAMS,
    },
  },
  {
    type: "function",
    function: {
      name: "get_comp_signal",
      description: "Anonymized aggregate salary-expectation statistics for comparable candidates (k-anonymous, k>=5).",
      parameters: COMMON_PARAMS,
    },
  },
];

export const ASK_SYSTEM_PROMPT = `You are Lexy's market intelligence analyst. You answer recruiter questions about hiring strategy using ONLY the data tools provided.

HARD RULES — these are absolute:
- You may only state facts returned by tool calls in THIS conversation. Never state a specific number, location, salary figure, or market claim from your own knowledge or training data.
- If tools return insufficient data ("no_data"), say so explicitly and suggest what data would help (e.g. run sourcing searches, record hires, add candidates). Never reason around a gap silently and never substitute an estimate.
- Always cite which tool result each claim came from and how recent it is (the asOf timestamp).
- ALWAYS call get_internal_bench FIRST — the caller's own talent pool is the free answer. If it has matches, present those candidates as the first recommendation BEFORE any external sourcing suggestion.
- Then use get_candidate_supply and get_hiring_velocity for the external picture, and get_comp_signal if compensation is relevant.
- End with a one-line confidence statement describing how much data backed this answer and which categories were missing.
- Keep the narrative concise and practical: a ranked recommendation, not an essay.`;

/** Second-pass prompt for the SEPARATE general-guidance channel (cold start).
 *  It must stay generic/directional; the server-side scrubber below is the
 *  hard backstop that removes any specific figure the model emits anyway. */
export const GENERAL_GUIDANCE_PROMPT = `You are Lexy's hiring advisor giving GENERAL industry guidance, because the caller's own platform has little or no data yet. Be CONCRETE and OPINIONATED about WHERE to look — this is your world knowledge, and it will be clearly labeled as such.

WHAT GOOD GUIDANCE LOOKS LIKE:
- NAME the specific talent markets best known for this exact role: countries, cities, and regions (e.g. for Java developers: Poland, India, Ukraine, Romania, Portugal, Brazil; for mechanical engineers: Germany, Michigan, Ohio, Mexico, India). Rank or group them (nearshore vs offshore, cost tier, timezone overlap) qualitatively.
- Name the channels that actually work for this role type (specific communities, platforms, conference circuits, university pipelines) — not generic "use job boards" filler.
- Call out practical trade-offs qualitatively: timezone overlap, English proficiency, visa/remote-contracting norms, market competitiveness.

ABSOLUTE RULES:
- NEVER state a specific number: no salary figures, no dollar amounts, no percentages, no counts, no dates, no statistics of any kind. Describe magnitudes qualitatively ("significantly lower cost", "deep talent pool", "highly competitive").
- NEVER name a specific person or claim knowledge of the caller's own candidates, jobs, or data.
- 4-6 punchy bullet points, plain language, tailored to the role in the question — never a generic sourcing lecture.`;

/**
 * Deterministic backstop for the general-guidance channel: DROP any sentence
 * containing a specific figure (currency amounts, percentages, "$142k"-style
 * shorthands, or standalone 3+ digit numbers). The model must not be able to
 * smuggle a fabricated specific into the "general knowledge" bucket — same
 * doctrine as buildInsufficientAnswer overriding the narrative.
 * Returns null when nothing generic survives.
 */
export function scrubGuidanceSpecifics(text: string): string | null {
  if (!text || !text.trim()) return null;
  // Digit-based figures PLUS spelled-out quantity claims ("ten percent",
  // "a hundred thousand dollars", "thousands of applicants") — fail-closed:
  // better to drop a borderline-generic sentence than surface a fabricated one.
  const SPECIFIC =
    /[$€£]\s?\d|\d[\d,]*\s?%|\b\d+(?:\.\d+)?\s?k\b|\b\d{3,}\b|\b(?:percent|per cent)\b|\b(?:hundred|thousand|million|billion)s?\b|\b(?:dollars|euros|pounds)\b/i;
  const kept: string[] = [];
  for (const line of text.split("\n")) {
    // Split each line into sentences so one bad claim doesn't kill a whole bullet.
    const sentences = line.split(/(?<=[.!?])\s+/);
    const safe = sentences.filter(s => !SPECIFIC.test(s)).join(" ").trim();
    // Drop bullets that became empty shells after scrubbing.
    if (safe && !/^[-•*\s]+$/.test(safe)) kept.push(safe);
  }
  const out = kept.join("\n").trim();
  return out.length >= 40 ? out : null;
}

/* ── Executor (tenant scope bound server-side) ────────────────────────────── */

export interface SanitizedToolArgs {
  role: string;
  skills?: string[];
  location?: string;
}

/** Strip anything the model shouldn't control; tenant scope NEVER comes from the model. */
export function sanitizeToolArgs(raw: unknown): SanitizedToolArgs | null {
  if (!raw || typeof raw !== "object") return null;
  const o = raw as Record<string, unknown>;
  const role = typeof o.role === "string" ? o.role.trim() : "";
  if (role.length < 2) return null;
  const skills = Array.isArray(o.skills)
    ? o.skills.filter((s): s is string => typeof s === "string").map(s => s.trim()).filter(Boolean).slice(0, 20)
    : undefined;
  const location = typeof o.location === "string" && o.location.trim() ? o.location.trim() : undefined;
  return { role, skills, location };
}

export type MarketToolExecutor = (
  tool: MarketToolName,
  args: SanitizedToolArgs,
) => Promise<ToolResult<any>>;

/** Default executor hitting the real Step-1 tools, scope pre-bound.
 *  tenantScope=null (platform admin) means platform-wide stats for the
 *  aggregate tools but NO "own pool" for internal bench (honest no_data). */
export function makeToolExecutor(tenantScope: string[] | null): MarketToolExecutor {
  return async (tool, args) => {
    switch (tool) {
      case "get_internal_bench":
        return getInternalBench({ role: args.role, skills: args.skills, tenantIds: tenantScope ?? [] });
      case "get_candidate_supply":
        return getCandidateSupply({ role: args.role, skills: args.skills, location: args.location, tenantScope });
      case "get_hiring_velocity":
        return getHiringVelocity({ role: args.role, location: args.location, tenantScope });
      case "get_comp_signal":
        return getCompSignal({ role: args.role, skills: args.skills, location: args.location });
    }
  };
}

/* ── Source/coverage builders (deterministic, from real executions) ───────── */

function sampleSizeOf(tool: MarketToolName, r: ToolResult<any>): number | undefined {
  if (r.status !== "ok") return undefined;
  switch (tool) {
    case "get_internal_bench": return (r as any).matchCount;
    case "get_candidate_supply": return (r as any).searchesInWindow;
    case "get_hiring_velocity": return (r as any).sampleSize;
    case "get_comp_signal": return (r as any).sampleSize;
  }
}

function summarize(tool: MarketToolName, r: ToolResult<any>): string {
  if (r.status === "no_data") return `no data — ${r.reason}`;
  const a = r as any;
  switch (tool) {
    case "get_internal_bench":
      return `${a.matchCount} matching candidate(s) already in your talent pool (${a.currentEmployeeCount} current employee(s))`;
    case "get_candidate_supply":
      return `${a.totalCandidatesFound} candidates found across ${a.searchesInWindow} search(es) in the last ${a.windowDays} days` + (a.trend ? `, trend ${a.trend}` : "");
    case "get_hiring_velocity":
      return `median ${a.medianDaysToFill} days to fill (n=${a.sampleSize}, ${a.scope} scope)`;
    case "get_comp_signal":
      return `expected range ~${a.medianLow}–${a.medianHigh} (n=${a.sampleSize}, anonymized aggregate)`;
  }
}

const TOOL_LABEL: Record<MarketToolName, string> = {
  get_internal_bench: "internal bench",
  get_candidate_supply: "candidate supply",
  get_hiring_velocity: "hiring velocity",
  get_comp_signal: "compensation signal",
};

export function buildConfidenceLine(sources: AskSource[]): string {
  const ok = sources.filter(s => s.status === "ok");
  const missing = sources.filter(s => s.status === "no_data");
  // Honesty: coverage is judged against ALL four canonical data categories,
  // not just the tools the model happened to call. A category the model never
  // consulted is listed explicitly as "not consulted" and blocks "full coverage".
  const consulted = new Set(sources.map(s => s.tool));
  const unconsulted = TOOL_ORDER.filter(t => !consulted.has(t));
  if (sources.length === 0) return "Confidence: none — no data tools were consulted, so no factual answer is possible.";
  if (ok.length === 0) {
    return `Confidence: none — all ${sources.length} data categories consulted (${sources.map(s => TOOL_LABEL[s.tool]).join(", ")}) returned insufficient data.`;
  }
  const backing = ok.map(s => `${TOOL_LABEL[s.tool]} (n=${s.sampleSize ?? "?"})`).join(", ");
  const gaps = missing.length ? `; missing: ${missing.map(s => TOOL_LABEL[s.tool]).join(", ")}` : "";
  const notConsulted = unconsulted.length
    ? `; not consulted: ${unconsulted.map(t => TOOL_LABEL[t]).join(", ")}`
    : "";
  const thin = ok.some(s => (s.sampleSize ?? 0) < 5) ? " Some sample sizes are thin — treat directional, not precise." : "";
  const full = missing.length === 0 && unconsulted.length === 0;
  return `Confidence: ${full ? "full coverage" : "partial coverage"} — backed by ${backing}${gaps}${notConsulted}.${thin}`;
}

/** Deterministic insufficiency answer — used INSTEAD of the model narrative when nothing had data. */
export function buildInsufficientAnswer(question: string, sources: AskSource[]): string {
  const lines = [
    `I don't have enough data to answer that reliably, and I won't guess.`,
  ];
  if (sources.length > 0) {
    lines.push(`I checked ${sources.length} data source(s) and none returned sufficient data:`);
    for (const s of sources) lines.push(`• ${TOOL_LABEL[s.tool]}: ${s.summary}`);
  } else {
    lines.push(`No data tools produced usable results for this question.`);
  }
  lines.push(
    `What would help: adding candidates to your talent pool, running sourcing searches for this role, and recording completed hires — each one unlocks a data category above.`,
  );
  return lines.join("\n");
}

/** Order citations internal-bench-first (when it has data), then by tool order. */
export function orderSources(sources: AskSource[]): AskSource[] {
  return [...sources].sort((a, b) => {
    const aBench = a.tool === "get_internal_bench" ? 0 : 1;
    const bBench = b.tool === "get_internal_bench" ? 0 : 1;
    if (aBench !== bBench) return aBench - bBench;
    return TOOL_ORDER.indexOf(a.tool) - TOOL_ORDER.indexOf(b.tool);
  });
}

/** Deterministic internal-first headline prepended to the narrative. */
export function benchHeadline(bench: ToolResult<InternalBenchOk> | undefined): string | null {
  if (!bench || bench.status !== "ok") return null;
  const b = bench as InternalBenchOk & { status: "ok"; asOf: string };
  const names = b.topMatches.slice(0, 3).map(m => m.name).filter(Boolean).join(", ");
  return `Start internal: ${b.matchCount} matching candidate(s) are already in your own talent pool${names ? ` (top matches: ${names})` : ""} — engage them before spending on external sourcing.`;
}

/* ── LLM plumbing (injectable for tests) ──────────────────────────────────── */

export type ChatMessage = OpenAI.Chat.Completions.ChatCompletionMessageParam;
export type ChatFn = (
  messages: ChatMessage[],
  tools: OpenAI.Chat.Completions.ChatCompletionTool[],
) => Promise<OpenAI.Chat.Completions.ChatCompletionMessage>;

let defaultClient: OpenAI | null = null;
function defaultChat(): ChatFn {
  if (!defaultClient) {
    defaultClient = new OpenAI({
      apiKey: process.env.AI_INTEGRATIONS_OPENAI_API_KEY ?? process.env.OPENAI_API_KEY,
      baseURL: process.env.AI_INTEGRATIONS_OPENAI_BASE_URL,
    });
  }
  const client = defaultClient;
  return async (messages, tools) => {
    const resp = await client.chat.completions.create({
      model: "gpt-4o",
      temperature: 0.2,
      messages,
      tools,
      tool_choice: "auto",
    });
    return resp.choices[0].message;
  };
}

const MAX_TOOL_ROUNDS = 6;

/* ── Main entrypoint ──────────────────────────────────────────────────────── */

export async function askMarketIntelligence(params: {
  question: string;
  /** Caller's allowed tenant ids (null = platform) — bound server-side, never model-supplied. */
  tenantScope: string[] | null;
  /** Test seams. */
  chat?: ChatFn;
  executor?: MarketToolExecutor;
  /** Separate seam for the general-guidance second pass. In production it
   *  defaults to the real client; when `chat` is injected (tests) and this
   *  is omitted, guidance is skipped so scripted sequences stay unchanged. */
  guidanceChat?: ChatFn;
}): Promise<AskResult> {
  const chat = params.chat ?? defaultChat();
  const guidanceChat = params.guidanceChat ?? (params.chat ? undefined : chat);
  const executor = params.executor ?? makeToolExecutor(params.tenantScope);

  const messages: ChatMessage[] = [
    { role: "system", content: ASK_SYSTEM_PROMPT },
    { role: "user", content: params.question },
  ];

  const sources: AskSource[] = [];
  /** Latest result per tool (dedup citations; last execution wins). */
  const latest = new Map<MarketToolName, { source: AskSource; result: ToolResult<any> }>();
  /** EVERY tool call attempted (incl. duplicates + rejected) — grounding audit trail. */
  const executions: AskExecution[] = [];
  let narrative = "";

  for (let round = 0; round <= MAX_TOOL_ROUNDS; round++) {
    const msg = await chat(messages, MARKET_TOOL_DEFS);
    const toolCalls = (msg.tool_calls ?? []).filter(tc => tc.type === "function");

    if (toolCalls.length === 0) {
      narrative = typeof msg.content === "string" ? msg.content.trim() : "";
      break;
    }

    messages.push(msg as ChatMessage);
    for (const tc of toolCalls) {
      const name = tc.function.name as MarketToolName;
      let payload: ToolResult<any> | { error: string };
      let source: AskSource | null = null;

      if (!TOOL_ORDER.includes(name)) {
        payload = { error: `unknown tool ${tc.function.name}` };
        executions.push({ round, tool: tc.function.name, outcome: "rejected_unknown_tool" });
      } else {
        let rawArgs: unknown = null;
        try { rawArgs = JSON.parse(tc.function.arguments || "{}"); } catch { /* invalid JSON */ }
        const args = sanitizeToolArgs(rawArgs);
        if (!args) {
          payload = { error: "invalid arguments — 'role' (string, >=2 chars) is required" };
          executions.push({ round, tool: name, outcome: "rejected_invalid_args" });
        } else {
          try {
            const result = await executor(name, args);
            payload = result;
            source = {
              tool: name,
              params: { role: args.role, ...(args.skills?.length ? { skills: args.skills } : {}), ...(args.location ? { location: args.location } : {}) },
              asOf: result.asOf,
              status: result.status,
              sampleSize: sampleSizeOf(name, result),
              summary: summarize(name, result),
            };
            latest.set(name, { source, result });
            executions.push({ round, tool: name, outcome: result.status, params: source.params, asOf: result.asOf, sampleSize: source.sampleSize, summary: source.summary });
          } catch (err: any) {
            logger.error({ err: err?.message, tool: name }, "[market-intel-ask] tool execution failed");
            payload = { error: "tool execution failed" };
            executions.push({ round, tool: name, outcome: "execution_failed" });
          }
        }
      }
      // One structured log line per tool call — grep evt:"market_intel_tool_call".
      logger.info({ evt: "market_intel_tool_call", ...executions[executions.length - 1] }, "[market-intel-ask] tool call");
      messages.push({ role: "tool", tool_call_id: tc.id, content: JSON.stringify(payload) });
    }

    if (round === MAX_TOOL_ROUNDS) {
      // Budget exhausted — one final forced answer without more tools.
      const final = await chat([...messages, { role: "system", content: "Tool budget exhausted. Answer now from the tool results above only." }], []);
      narrative = typeof final.content === "string" ? final.content.trim() : "";
    }
  }

  // Citations from ACTUAL executions only (latest per tool), internal-first.
  for (const t of TOOL_ORDER) {
    const entry = latest.get(t);
    if (entry) sources.push(entry.source);
  }
  const ordered = orderSources(sources);

  const okCount = ordered.filter(s => s.status === "ok").length;
  const coverage: AskCoverage = {
    toolsCalled: ordered.length,
    okCount,
    noDataCount: ordered.length - okCount,
    sufficient: okCount > 0,
  };
  const confidence = buildConfidenceLine(ordered);

  let answer: string;
  if (!coverage.sufficient) {
    // HARD GUARANTEE: no data → no confident narrative, period.
    answer = buildInsufficientAnswer(params.question, ordered);
  } else {
    const headline = benchHeadline(latest.get("get_internal_bench")?.result as ToolResult<InternalBenchOk> | undefined);
    const body = narrative || "The data tools returned results, but no narrative was produced — see the cited sources below.";
    answer = headline && !body.startsWith("Start internal:") ? `${headline}\n\n${body}` : body;
  }

  // Structured bench cards from the REAL tool result only (never the model).
  const benchResult = latest.get("get_internal_bench")?.result as (ToolResult<InternalBenchOk> & { status: string }) | undefined;
  const benchMatches =
    benchResult && benchResult.status === "ok" && Array.isArray((benchResult as any).topMatches)
      ? (benchResult as any).topMatches.map((m: any) => ({
          candidateId: String(m.candidateId),
          name: String(m.name ?? ""),
          title: String(m.title ?? ""),
          matchScore: Number(m.matchScore ?? 0),
          isCurrentEmployee: Boolean(m.isCurrentEmployee),
        }))
      : undefined;

  // ── SEPARATE lower-trust channel: general industry guidance for cold-start ──
  // Only when platform data is thin (zero or one category). Best-effort: any
  // failure yields no guidance, never a broken answer. The deterministic
  // scrubber strips every sentence containing a specific figure so the model
  // cannot route fabricated specifics around the tool-only-facts constraint.
  let generalGuidance: string | undefined;
  if (okCount <= 1 && guidanceChat) {
    try {
      const g = await guidanceChat(
        [
          { role: "system", content: GENERAL_GUIDANCE_PROMPT },
          { role: "user", content: params.question },
        ],
        [],
      );
      const raw = typeof g.content === "string" ? g.content.trim() : "";
      generalGuidance = scrubGuidanceSpecifics(raw) ?? undefined;
    } catch (err: any) {
      logger.warn({ err: err?.message }, "[market-intel-ask] general guidance pass failed (non-blocking)");
    }
  }

  return {
    answer,
    confidence,
    sources: ordered,
    coverage,
    executions,
    ...(benchMatches ? { benchMatches } : {}),
    ...(generalGuidance ? { generalGuidance } : {}),
  };
}
