/**
 * routes/outreach-reply.ts — One-Click Email Reply Handler
 *
 * ─── What this file does ────────────────────────────────────────────────────
 * Handles the public URL that candidates land on when they click a quick-reply
 * button in an outreach email ("I'm interested" / "Not for this role" /
 * "Stop emailing me"). The token in the URL is verified by outreach-reply-tokens.ts
 * and then the appropriate action is applied atomically.
 *
 * ─── Two token namespaces ────────────────────────────────────────────────────
 *   GET /outreach/reply/:token      Enrollment tokens (campaign sequences)
 *     Resolves to an outreach_enrollments row. Actions applied:
 *       interested        → notifyRecruiterOfReply(classification=interested)
 *       not_interested_job → cancel enrollment + notifyRecruiter(not_interested)
 *       dnc               → cancel enrollment + recordRejection + doNotContact
 *
 *   GET /outreach/reply-msg/:token  Message tokens (orchestrator one-off emails)
 *     Resolves to an outreach_messages row. Same action cascade but stamped on
 *     the message row (repliedAt, replyAction) rather than the enrollment row.
 *
 * ─── Action mapping ──────────────────────────────────────────────────────────
 * QUICK_REPLY_TO_CLASSIFICATION maps token actions → ReplyClassification so
 * the recruiter notify logic is shared with the webhook inbound-email path.
 *
 * ─── DNC cascade ─────────────────────────────────────────────────────────────
 * dnc action calls recordRejection() (rejection record + optional email) and
 * then sets candidates.doNotContact = true. All open enrollments for the
 * candidate are cancelled at the same time so they receive no further outreach.
 *
 * ─── Called by ───────────────────────────────────────────────────────────────
 *   Email buttons generated by buildQuickReplyBlocks() in outreach-reply-tokens.ts
 *   Mounted at GET /api/outreach/reply/:token and /api/outreach/reply-msg/:token
 *   by routes/index.ts.
 */
import { Router, type IRouter } from "express";
import { z } from "zod";
import { validate } from "../middlewares/validate";
import {
  db,
  outreachEnrollmentsTable,
  outreachMessagesTable,
  sourcedCandidatesTable,
  candidatesTable,
  candidateRejectionsTable,
  jobsTable,
} from "@workspace/db";
import { and, eq, sql, inArray } from "drizzle-orm";
import {
  verifyReplyToken,
  verifyMessageReplyToken,
  type ReplyAction,
} from "../lib/outreach-reply-tokens";
import { recordAudit } from "../lib/audit";
import { recordRejection } from "../lib/record-rejection";
import { changeCandidateStage } from "../lib/change-candidate-stage.js";
import { notifyRecruiterOfReply, type ReplyClassification } from "../lib/recruiter-reply-notify";
import { logger } from "../lib/logger";

const router: IRouter = Router();

/* Both POST endpoints derive the action from the signed token in the URL —
 * `req.body` is intentionally unused. Strict empty-body validation makes the
 * contract explicit and stops any future caller from smuggling a forged
 * `action`/`enrollmentId` field hoping a later refactor picks it up. */
const OutreachReplyBody = z.object({}).strict();

const QUICK_REPLY_TO_CLASSIFICATION: Record<ReplyAction, ReplyClassification> = {
  interested: "interested",
  not_interested_job: "not_interested",
  dnc: "unsubscribe",
};

const QUICK_REPLY_BODY: Record<ReplyAction, string> = {
  interested: "[Quick reply: Yes, I'm interested]",
  not_interested_job: "[Quick reply: Not for this role]",
  dnc: "[Quick reply: Don't contact me]",
};

/**
 * Emit the same engagement signals an inbound "interested" email reply would.
 *
 * A candidate clicking the "I'm interested" quick-reply button is functionally
 * identical to them replying "yes, interested" by email — yet historically only
 * the inbound-email webhook path (webhooks.ts Paths A & B) recorded the
 * Connection Engine events, so a quick-reply candidate showed "responded
 * interested" / advanced to an interview while their Connection Strength stayed
 * at 0. This mirrors that webhook emission for the quick-reply route.
 *
 * Best-effort: any failure is logged and swallowed so it can never break the
 * candidate-facing reply confirmation. `candidateId` is the CANONICAL
 * (normalized) candidate id — connection events are keyed by it.
 */
async function recordInterestedReplyConnectionEvents(opts: {
  /** Canonical (normalized) candidate id — connection events are keyed by it. */
  candidateId: string | null | undefined;
  /**
   * All ids this candidate may be stored under on `outreach_messages.candidate_id`
   * (canonical id, sourced-row id, and the reply's own candidate_id). The
   * "sent within 24 h" lookup matches ANY of them — message rows in this codebase
   * are keyed by EITHER the sourced id OR the canonical id, so a canonical-only
   * lookup would silently miss the +10 for true <24h replies.
   */
  lookupCandidateIds: (string | null | undefined)[];
  jobId: string | null | undefined;
  employerId: string | null | undefined;
  context: string;
}): Promise<void> {
  const { candidateId, jobId, employerId, context } = opts;
  if (!candidateId) {
    // Recorded "interested" but the candidate has no canonical record, so there
    // is no candidate the recruiter detail (keyed by canonical id) could read a
    // score from. Surface it rather than dropping the signal silently.
    logger.warn({ context, jobId }, "[quick-reply] interested reply has no canonical candidate id — connection events skipped");
    return;
  }
  const lookupIds = Array.from(
    new Set(opts.lookupCandidateIds.filter((id): id is string => !!id)),
  );

  // Candidate-side insights (mirrors webhooks "replied_to_message").
  try {
    const { recordCandidateConnectionEvent, recalculateCandidateInsights } =
      await import("../lib/candidateConnectionEngine.js");
    await recordCandidateConnectionEvent({
      candidateId,
      eventType: "replied_to_message",
      jobId: jobId ?? null,
    });
    await recalculateCandidateInsights(candidateId, jobId ?? null);
  } catch (err: any) {
    logger.error({ err: err?.message, context }, "[quick-reply] candidate Connection Engine update failed");
  }

  // Employer-side Connection Strength (mirrors webhooks "replied_to_outreach"
  // + "response_within_24h" + "accepted_intro").
  try {
    const { recordConnectionEvent, recalculateConnectionScore } =
      await import("../lib/connectionEngine.js");
    await recordConnectionEvent({
      candidateId,
      eventType: "replied_to_outreach",
      jobId: jobId ?? null,
      employerId: employerId ?? null,
    });
    // +10 if the candidate replied within 24 h of the last outreach send.
    const [lastSent] = await db.select({ sentAt: outreachMessagesTable.sentAt })
      .from(outreachMessagesTable)
      .where(and(
        inArray(outreachMessagesTable.candidateId, lookupIds),
        eq(outreachMessagesTable.status, "sent"),
      ))
      .orderBy(sql`${outreachMessagesTable.sentAt} DESC`)
      .limit(1);
    if (lastSent?.sentAt) {
      const hoursElapsed = (Date.now() - new Date(lastSent.sentAt).getTime()) / 36e5;
      if (hoursElapsed <= 24) {
        await recordConnectionEvent({
          candidateId,
          eventType: "response_within_24h",
          jobId: jobId ?? null,
          employerId: employerId ?? null,
        });
      }
    }
    // +15 — the quick-reply "interested" button is an explicit intro acceptance.
    await recordConnectionEvent({
      candidateId,
      eventType: "accepted_intro",
      jobId: jobId ?? null,
      employerId: employerId ?? null,
    });
    await recalculateConnectionScore(candidateId, jobId ?? null, employerId ?? null);
  } catch (err: any) {
    logger.error({ err: err?.message, context }, "[quick-reply] employer Connection Engine update failed");
  }
}

/**
 * Quick-reply links embedded in outreach emails.
 *
 * Two-step flow to defeat link prefetchers (Gmail / Outlook / antivirus
 * scanners aggressively follow GET URLs and would otherwise auto-fire
 * Do-Not-Contact for innocent candidates):
 *
 *   GET  /api/outreach/reply/:token   — renders a confirmation page with
 *                                       a POST form. SAFE for prefetchers
 *                                       because it never mutates state.
 *   POST /api/outreach/reply/:token   — actually applies the action,
 *                                       atomically and idempotently.
 *
 * Actions:
 *   • interested        — equivalent to a positive reply; triggers the
 *                         existing interview-invite flow.
 *   • not_interested_job — declines THIS job only. The candidate stays
 *                         contactable for every other job. We only stop
 *                         the enrollment; sourced_candidates is NOT a
 *                         per-job table in this schema, so we record
 *                         the per-job decline inside raw_data.rejectedJobs
 *                         keyed by jobId rather than mutating the global
 *                         stage field.
 *   • dnc               — global do-not-contact across the platform.
 */

router.get("/outreach/reply/:token", (req, res) => {
  const v = verifyReplyToken(req.params.token);
  if (!v.ok) {
    res.status(400).type("html").send(renderError(
      "Link no longer valid",
      v.error === "expired"
        ? "This quick-reply link has expired. Please reply to the original email instead."
        : "We couldn't verify this link. Please reply to the original email instead.",
    ));
    return;
  }
  res.status(200).type("html").send(renderConfirm(req.params.token, v.action));
});

router.post("/outreach/reply/:token", validate({ body: OutreachReplyBody }), async (req, res) => {
  const v = verifyReplyToken(req.params.token);
  if (!v.ok) {
    res.status(400).type("html").send(renderError(
      "Link no longer valid",
      v.error === "expired"
        ? "This quick-reply link has expired."
        : "We couldn't verify this link.",
    ));
    return;
  }
  const { enrollmentId, action } = v;

  const [enrBefore] = await db.select().from(outreachEnrollmentsTable)
    .where(eq(outreachEnrollmentsTable.id, enrollmentId)).limit(1);
  if (!enrBefore) {
    res.status(404).type("html").send(renderError("Not found",
      "We couldn't find this outreach. It may have been removed."));
    return;
  }

  // Atomic claim: only the FIRST request gets to mutate state. Concurrent
  // requests (double-tap, mobile retry, two devices) and any prefetcher
  // that somehow learns to POST are all harmlessly serialised. Subsequent
  // claims on the same row return zero rows because the JSONB key is
  // already populated.
  const nowIso = new Date().toISOString();
  const claim: any = await db.execute(sql`
    UPDATE outreach_enrollments
       SET recipient_data = COALESCE(recipient_data, '{}'::jsonb)
                          || jsonb_build_object(
                               'quickReplyAction', CAST(${action} AS text),
                               'quickReplyAt',     CAST(${nowIso} AS text)
                             ),
           updated_at = now()
     WHERE id = ${enrollmentId}
       AND (recipient_data->>'quickReplyAction') IS NULL
     RETURNING id
  `);
  const claimed = Array.isArray(claim) ? claim.length : (claim?.rows?.length ?? claim?.rowCount ?? 0);

  if (!claimed) {
    // Already actioned. Look up which action was recorded so the user
    // sees the right "already done" message instead of a generic one.
    const [enrNow] = await db.select().from(outreachEnrollmentsTable)
      .where(eq(outreachEnrollmentsTable.id, enrollmentId)).limit(1);
    const prior = (enrNow?.recipientData as any)?.quickReplyAction;
    res.status(200).type("html").send(renderResult(
      "Already recorded",
      prior === action
        ? "We already received this response — thanks again. No further action needed."
        : "You've already responded to this outreach with a different action, so we'll keep that on file.",
      "#374151",
    ));
    return;
  }

  // We hold the claim — apply side effects. Failures here cannot be
  // retried by the candidate, so any DB error is logged and surfaced.
  const [sc] = await db.select().from(sourcedCandidatesTable)
    .where(eq(sourcedCandidatesTable.id, enrBefore.candidateId)).limit(1);
  const now = new Date();

  let title = "", message = "", color = "#0f6f3a";

  try {
    if (action === "interested") {
      await db.update(outreachEnrollmentsTable)
        .set({ status: "replied", repliedAt: now, updatedAt: now } as any)
        .where(eq(outreachEnrollmentsTable.id, enrollmentId));

      try {
        const { sendInterviewInviteFromReply } = await import("../lib/agents/interview-reply");
        await sendInterviewInviteFromReply({
          jobId: enrBefore.jobId,
          sourcedId: sc?.id ?? enrBefore.candidateId,
          replyBody: "[Quick reply: Yes, I'm interested]",
        });
      } catch (err: any) {
        logger.error({ err: err?.message, enrollmentId }, "[quick-reply] interview invite failed");
      }

      await recordInterestedReplyConnectionEvents({
        candidateId: sc?.normalizedCandidateId ?? null,
        lookupCandidateIds: [sc?.normalizedCandidateId, sc?.id, enrBefore.candidateId],
        jobId: enrBefore.jobId,
        employerId: enrBefore.tenantId,
        context: `enrollment:${enrollmentId}`,
      });

      title = "Great — we're on it!";
      message = "Thanks for confirming your interest. You'll receive an interview invite by email within a few minutes.";
      color = "#0f6f3a";
    }

    else if (action === "not_interested_job") {
      // Stop the enrollment AND move the candidate to the Rejected
      // column for THIS job. We explicitly stamp raw.jobId so that
      // pipeline-stages's per-job filter (`raw.jobId === jobId || !raw.jobId`)
      // matches ONLY this job — without the stamp, an unattributed
      // sourced row would surface as rejected on every job board.
      // Mirrors the inbound text-reply path in pipeline.ts (`negative`
      // sentiment → 'rejected').
      await db.update(outreachEnrollmentsTable)
        .set({ status: "stopped", updatedAt: now } as any)
        .where(eq(outreachEnrollmentsTable.id, enrollmentId));

      if (sc) {
        const raw = (sc.rawData as any) || {};
        const rejectedJobs = { ...(raw.rejectedJobs || {}) };
        rejectedJobs[enrBefore.jobId] = {
          rejectedAt: now.toISOString(),
          reason: "candidate_declined_this_role",
          channel: "quick_reply_button",
        };
        const declineRawPatch = {
          jobId: raw.jobId ?? enrBefore.jobId,
          rejectionReason: "Candidate declined opportunity (one-click reply)",
          rejectedAt: now.toISOString(),
          rejectedJobs,
        };
        if (sc.normalizedCandidateId && enrBefore.jobId) {
          // Candidate clicked the one-click "not for this role" reply link → candidate actor.
          await changeCandidateStage({
            tenantId: enrBefore.tenantId ?? "",
            candidateId: sc.normalizedCandidateId,
            jobId: enrBefore.jobId,
            to: "rejected",
            actor: { type: "candidate", role: "candidate", id: sc.normalizedCandidateId },
            source: "quick_reply",
            reason: "Candidate declined opportunity (one-click reply)",
            sourcedId: sc.id,
            sourcedRawDataPatch: declineRawPatch,
            metadata: { action: "not_interested_job", enrollmentId },
          });
        } else {
          // stage-write-exempt: sourced row has no canonical candidateId to key the STAGE_CHANGED event/audit rows
          await db.update(sourcedCandidatesTable).set({
            rawData: { ...raw, stage: "rejected", ...declineRawPatch },
          }).where(eq(sourcedCandidatesTable.id, sc.id));
        }
      }

      // Audit row, deduped per (jobId, sourcedId) so each per-job
      // self-decline is recorded even if the candidate was already
      // rejected for a different job earlier. Skip the polite "we
      // regret to inform you" email — the candidate just self-declined.
      const alreadyAudited = sc
        ? (await db.select({ id: candidateRejectionsTable.id })
            .from(candidateRejectionsTable)
            .where(and(
              eq(candidateRejectionsTable.sourcedId, sc.id),
              eq(candidateRejectionsTable.jobId, enrBefore.jobId),
            )).limit(1)).length > 0
        : false;
      if (!alreadyAudited) {
        try {
          await recordRejection({
            tenantId: enrBefore.tenantId,
            jobId: enrBefore.jobId,
            sourcedId: sc?.id ?? null,
            candidateId: sc?.normalizedCandidateId ?? null,
            rejectedByRole: "system",
            reason: "Candidate declined opportunity",
            notes: "Candidate clicked \"Not for this role\" reply button.",
            fromStage: (sc?.rawData as any)?.stage ?? null,
            sendEmail: false,
          });
        } catch (err: any) {
          logger.error({ err: err?.message, enrollmentId }, "[quick-reply] recordRejection failed");
        }
      }

      const [job] = await db.select({ title: jobsTable.title })
        .from(jobsTable).where(eq(jobsTable.id, enrBefore.jobId)).limit(1);
      title = "Got it — we'll skip this role";
      message = `Thanks for letting us know. We've removed you from outreach for ${job?.title ?? "this role"}. You'll still hear from us if a different opportunity looks like a great fit — or click "Don't contact me" in any email to opt out entirely.`;
      color = "#7c4a03";
    }

    else if (action === "dnc") {
      // Global do-not-contact AND drop them from the active pipeline
      // for THIS job. Other jobs are unaffected at the kanban level
      // (per-job filtering) but the global doNotContact flag prevents
      // any future outreach across all jobs.
      await db.update(outreachEnrollmentsTable)
        .set({ status: "stopped", updatedAt: now } as any)
        .where(eq(outreachEnrollmentsTable.id, enrollmentId));

      const dncFields = {
        doNotContact: true,
        dncAt: now,
        dncReason: "candidate_quick_reply_dnc",
        updatedAt: now,
      } as any;

      let dncOk = false;
      if (enrBefore.recipientEmail) {
        try {
          await db.update(candidatesTable).set(dncFields)
            .where(and(
              eq(candidatesTable.tenantId, enrBefore.tenantId),
              eq(candidatesTable.email, enrBefore.recipientEmail),
            ));
          dncOk = true;
        } catch (err: any) {
          logger.error({ err: err?.message, enrollmentId }, "[quick-reply] DNC by email failed");
        }
      }
      if (sc?.normalizedCandidateId) {
        try {
          await db.update(candidatesTable).set(dncFields)
            .where(eq(candidatesTable.id, sc.normalizedCandidateId));
          dncOk = true;
        } catch (err: any) {
          logger.error({ err: err?.message, enrollmentId }, "[quick-reply] DNC by normalized id failed");
        }
      }
      const wasAlreadyRejected = (sc?.rawData as any)?.stage === "rejected";
      if (sc) {
        const raw = (sc.rawData as any) || {};
        const dncRawPatch = {
          rejectionReason: "Do not contact (candidate request)",
          rejectedAt: now.toISOString(),
          doNotContact: true,
          dncAt: now.toISOString(),
          dncChannel: "quick_reply_button",
        };
        if (sc.normalizedCandidateId && enrBefore.jobId) {
          // Candidate clicked the one-click "don't contact me" reply link → candidate actor.
          await changeCandidateStage({
            tenantId: enrBefore.tenantId ?? "",
            candidateId: sc.normalizedCandidateId,
            jobId: enrBefore.jobId,
            to: "rejected",
            actor: { type: "candidate", role: "candidate", id: sc.normalizedCandidateId },
            source: "quick_reply",
            reason: "Do not contact (candidate request)",
            sourcedId: sc.id,
            sourcedRawDataPatch: dncRawPatch,
            metadata: { action: "dnc", enrollmentId },
          });
        } else {
          // stage-write-exempt: sourced row has no canonical candidateId to key the STAGE_CHANGED event/audit rows
          await db.update(sourcedCandidatesTable).set({
            rawData: { ...raw, stage: "rejected", ...dncRawPatch },
          }).where(eq(sourcedCandidatesTable.id, sc.id));
        }
      }
      if (!wasAlreadyRejected) {
        try {
          await recordRejection({
            tenantId: enrBefore.tenantId,
            jobId: enrBefore.jobId,
            sourcedId: sc?.id ?? null,
            candidateId: sc?.normalizedCandidateId ?? null,
            rejectedByRole: "system",
            reason: "Do not contact (candidate request)",
            notes: "Candidate clicked \"Don't contact me\" reply button — global DNC applied.",
            fromStage: (sc?.rawData as any)?.stage ?? null,
            sendEmail: false,
          });
        } catch (err: any) {
          logger.error({ err: err?.message, enrollmentId }, "[quick-reply] recordRejection (DNC) failed");
        }
      }

      if (!dncOk) {
        // Surface the partial failure rather than silently swallowing it.
        // Audit will reflect that DNC propagation needs manual follow-up.
        logger.warn({ enrollmentId, email: enrBefore.recipientEmail },
          "[quick-reply] DNC clicked but no candidate row was updated");
      }

      title = "You've been unsubscribed";
      message = "We've removed you from all outreach across the platform. You won't hear from us again. Sorry for the noise.";
      color = "#991b1b";
    }

    // Notify the assigned recruiter — both an in-app inbox row AND an
    // email (or digest entry, depending on their preference). Without
    // this, candidates clicking quick-reply buttons would silently apply
    // side effects without ever surfacing to the recruiter.
    try {
      await notifyRecruiterOfReply({
        tenantId: enrBefore.tenantId,
        jobId: enrBefore.jobId,
        candidateId: sc?.normalizedCandidateId ?? sc?.id ?? enrBefore.candidateId,
        candidateName: enrBefore.recipientName,
        candidateEmail: enrBefore.recipientEmail,
        classification: QUICK_REPLY_TO_CLASSIFICATION[action],
        body: QUICK_REPLY_BODY[action],
        campaignId: enrBefore.campaignId,
      });
    } catch (err: any) {
      logger.error({ err: err?.message, enrollmentId, action },
        "[quick-reply] notifyRecruiterOfReply failed");
    }

    void recordAudit({
      tenantId: enrBefore.tenantId,
      actorType: "candidate",
      actorId: sc?.id ?? null,
      actorLabel: enrBefore.recipientName || enrBefore.recipientEmail,
      subjectType: "candidate",
      subjectId: sc?.id ?? null,
      subjectLabel: enrBefore.recipientName || enrBefore.recipientEmail,
      channel: "email",
      direction: "inbound",
      action: `outreach.quick_reply.${action}`,
      title: `Candidate quick-reply: ${action}`,
      metadata: { enrollmentId, jobId: enrBefore.jobId },
    });

    res.status(200).type("html").send(renderResult(title, message, color));
  } catch (err: any) {
    logger.error({ err: err?.message, enrollmentId, action }, "[quick-reply] handler failed");
    res.status(500).type("html").send(renderError(
      "Something went wrong",
      "We couldn't fully record your response. Please reply to the original email so we don't miss it.",
    ));
  }
});

/**
 * Message-scoped quick-reply (orchestrator path).
 *
 * Same two-step GET-confirm / POST-mutate flow as the enrollment route
 * above, but operates on `outreach_messages` rows instead of campaign
 * enrollments. Used for emails sent by the Screening Agent's outreach
 * dispatcher in `orchestrator.ts`, which doesn't create an enrollment.
 */
router.get("/outreach/reply-msg/:token", (req, res) => {
  const v = verifyMessageReplyToken(req.params.token);
  if (!v.ok) {
    res.status(400).type("html").send(renderError(
      "Link no longer valid",
      v.error === "expired"
        ? "This quick-reply link has expired. Please reply to the original email instead."
        : "We couldn't verify this link. Please reply to the original email instead.",
    ));
    return;
  }
  res.status(200).type("html").send(renderConfirmMsg(req.params.token, v.action));
});

router.post("/outreach/reply-msg/:token", validate({ body: OutreachReplyBody }), async (req, res) => {
  const v = verifyMessageReplyToken(req.params.token);
  if (!v.ok) {
    res.status(400).type("html").send(renderError(
      "Link no longer valid",
      v.error === "expired" ? "This quick-reply link has expired." : "We couldn't verify this link.",
    ));
    return;
  }
  const { messageId, action } = v;

  const [msgBefore] = await db.select().from(outreachMessagesTable)
    .where(eq(outreachMessagesTable.id, messageId)).limit(1);
  if (!msgBefore) {
    res.status(404).type("html").send(renderError("Not found",
      "We couldn't find this outreach. It may have been removed."));
    return;
  }

  // Atomic claim: only the first request mutates state. Concurrent or
  // repeated clicks (mobile retries, double-tap, prefetcher races) all
  // serialise harmlessly because the column is set on the first write.
  const sentimentMap: Record<ReplyAction, string> = {
    interested: "positive",
    not_interested_job: "negative",
    dnc: "do_not_contact",
  };
  const now = new Date();
  const claim: any = await db.execute(sql`
    UPDATE outreach_messages
       SET reply_sentiment = ${sentimentMap[action]},
           replied_at      = ${now}
     WHERE id = ${messageId}
       AND reply_sentiment IS NULL
     RETURNING id
  `);
  const claimed = Array.isArray(claim) ? claim.length : (claim?.rows?.length ?? claim?.rowCount ?? 0);

  if (!claimed) {
    const prior = msgBefore.replySentiment;
    res.status(200).type("html").send(renderResult(
      "Already recorded",
      prior === sentimentMap[action]
        ? "We already received this response — thanks again. No further action needed."
        : "You've already responded to this outreach with a different action, so we'll keep that on file.",
      "#374151",
    ));
    return;
  }

  // Resolve the candidate so we can apply DNC / decline side effects.
  // outreach_messages.candidate_id can point at EITHER a sourced row
  // (orchestrator-emitted messages) or a normalized candidate row
  // (other flows). Probe both, and if we found a normalized candidate
  // also pull the linked sourced row so the kanban-stage update lands.
  const [cand] = await db.select().from(candidatesTable)
    .where(eq(candidatesTable.id, msgBefore.candidateId)).limit(1);
  let sc: typeof sourcedCandidatesTable.$inferSelect | undefined;
  {
    const [scById] = await db.select().from(sourcedCandidatesTable)
      .where(eq(sourcedCandidatesTable.id, msgBefore.candidateId)).limit(1);
    if (scById) {
      sc = scById;
    } else if (cand) {
      // Match purely on the normalized candidate id — NOT the message's
      // tenant. The sourced row lives in the candidate's HOME tenant, which
      // for a platform-pool candidate sourced onto another tenant's job is
      // different from the job/message tenant. Filtering by msgBefore.tenantId
      // here silently failed to resolve the sourced row in that cross-tenant
      // case, so the interview-invite flow received the normalized candidate
      // id as a bogus sourcedId and bailed with "Sourced candidate not found".
      const scByNormRows = await db.select().from(sourcedCandidatesTable)
        .where(eq(sourcedCandidatesTable.normalizedCandidateId, cand.id))
        .limit(10);
      // A platform-pool candidate can be sourced onto multiple jobs (and
      // tenants). Prefer the sourced row tied to THIS reply's job before
      // falling back, so a later stage/session write never mutates an
      // unrelated sourced row.
      const scByNorm = scByNormRows.find(
        (r) => (r.rawData as any)?.jobId === msgBefore.jobId,
      ) ?? scByNormRows[0];
      if (scByNorm) sc = scByNorm;
    }
  }

  let title = "", message = "", color = "#0f6f3a";
  try {
    if (action === "interested") {
      // Mirror the enrollment path: trigger the interview-invite flow.
      try {
        const { sendInterviewInviteFromReply } = await import("../lib/agents/interview-reply");
        const inviteResult = await sendInterviewInviteFromReply({
          jobId: msgBefore.jobId,
          sourcedId: sc?.id ?? cand?.id ?? msgBefore.candidateId,
          replyBody: "[Quick reply: Yes, I'm interested]",
        });
        if (!inviteResult.ok) {
          logger.error(
            { messageId, jobId: msgBefore.jobId, error: inviteResult.error },
            "[quick-reply-msg] interview invite returned not-ok",
          );
        }
      } catch (err: any) {
        logger.error({ err: err?.message, messageId }, "[quick-reply-msg] interview invite failed");
      }

      await recordInterestedReplyConnectionEvents({
        candidateId: cand?.id ?? sc?.normalizedCandidateId ?? null,
        lookupCandidateIds: [cand?.id, sc?.normalizedCandidateId, sc?.id, msgBefore.candidateId],
        jobId: msgBefore.jobId,
        employerId: msgBefore.tenantId ?? (sc as any)?.tenantId ?? null,
        context: `message:${messageId}`,
      });

      title = "Great — we're on it!";
      message = "Thanks for confirming your interest. You'll receive an interview invite by email within a few minutes.";
      color = "#0f6f3a";
    }

    else if (action === "not_interested_job") {
      // Per-job decline: flip raw.stage to 'rejected' so the kanban
      // moves them to the Rejected column for THIS job, stamp raw.jobId
      // so the per-job filter in pipeline-stages can't accidentally
      // surface this rejection on other job boards, and keep the
      // rejectedJobs map for analytics. Mirrors the inbound text-reply
      // path in pipeline.ts (`negative` sentiment → 'rejected').
      if (sc) {
        const raw = (sc.rawData as any) || {};
        const rejectedJobs = { ...(raw.rejectedJobs || {}) };
        rejectedJobs[msgBefore.jobId] = {
          rejectedAt: now.toISOString(),
          reason: "candidate_declined_this_role",
          channel: "quick_reply_button",
        };
        const declineRawPatch = {
          jobId: raw.jobId ?? msgBefore.jobId,
          rejectionReason: "Candidate declined opportunity (one-click reply)",
          rejectedAt: now.toISOString(),
          rejectedJobs,
        };
        if (sc.normalizedCandidateId && msgBefore.jobId) {
          // Candidate clicked the one-click "not for this role" reply link → candidate actor.
          await changeCandidateStage({
            tenantId: msgBefore.tenantId ?? (sc as any).tenantId ?? "",
            candidateId: sc.normalizedCandidateId,
            jobId: msgBefore.jobId,
            to: "rejected",
            actor: { type: "candidate", role: "candidate", id: sc.normalizedCandidateId },
            source: "quick_reply",
            reason: "Candidate declined opportunity (one-click reply)",
            sourcedId: sc.id,
            sourcedRawDataPatch: declineRawPatch,
            metadata: { action: "not_interested_job", messageId },
          });
        } else {
          // stage-write-exempt: sourced row has no canonical candidateId to key the STAGE_CHANGED event/audit rows
          await db.update(sourcedCandidatesTable).set({
            rawData: { ...raw, stage: "rejected", ...declineRawPatch },
          }).where(eq(sourcedCandidatesTable.id, sc.id));
        }
      }
      // Audit row, deduped per (jobId, sourcedId) so each per-job
      // self-decline gets its own record. Skip the polite "we regret
      // to inform you" email — the candidate just self-declined.
      const alreadyAudited = sc
        ? (await db.select({ id: candidateRejectionsTable.id })
            .from(candidateRejectionsTable)
            .where(and(
              eq(candidateRejectionsTable.sourcedId, sc.id),
              eq(candidateRejectionsTable.jobId, msgBefore.jobId),
            )).limit(1)).length > 0
        : false;
      if (!alreadyAudited) {
        try {
          await recordRejection({
            tenantId: msgBefore.tenantId,
            jobId: msgBefore.jobId,
            sourcedId: sc?.id ?? null,
            candidateId: sc?.normalizedCandidateId ?? cand?.id ?? null,
            rejectedByRole: "system",
            reason: "Candidate declined opportunity",
            notes: "Candidate clicked \"Not for this role\" reply button.",
            fromStage: (sc?.rawData as any)?.stage ?? null,
            sendEmail: false,
          });
        } catch (err: any) {
          logger.error({ err: err?.message, messageId }, "[quick-reply-msg] recordRejection failed");
        }
      }
      const [job] = await db.select({ title: jobsTable.title })
        .from(jobsTable).where(eq(jobsTable.id, msgBefore.jobId)).limit(1);
      title = "Got it — we'll skip this role";
      message = `Thanks for letting us know. We've removed you from outreach for ${job?.title ?? "this role"}. You'll still hear from us if a different opportunity looks like a great fit — or click "Don't contact me" in any email to opt out entirely.`;
      color = "#7c4a03";
    }

    else if (action === "dnc") {
      const dncFields = {
        doNotContact: true,
        dncAt: now,
        dncReason: "candidate_quick_reply_dnc",
        updatedAt: now,
      } as any;
      let dncOk = false;
      const candEmail = cand?.email ?? (sc?.rawData as any)?.email ?? null;
      if (candEmail) {
        try {
          await db.update(candidatesTable).set(dncFields)
            .where(and(
              eq(candidatesTable.tenantId, msgBefore.tenantId),
              eq(candidatesTable.email, candEmail),
            ));
          dncOk = true;
        } catch (err: any) {
          logger.error({ err: err?.message, messageId }, "[quick-reply-msg] DNC by email failed");
        }
      }
      if (sc?.normalizedCandidateId) {
        try {
          await db.update(candidatesTable).set(dncFields)
            .where(eq(candidatesTable.id, sc.normalizedCandidateId));
          dncOk = true;
        } catch (err: any) {
          logger.error({ err: err?.message, messageId }, "[quick-reply-msg] DNC by normalized id failed");
        }
      }
      if (sc) {
        const raw = (sc.rawData as any) || {};
        const dncRawPatch = {
          jobId: raw.jobId ?? msgBefore.jobId,
          rejectionReason: "Do not contact (candidate request)",
          rejectedAt: now.toISOString(),
          doNotContact: true,
          dncAt: now.toISOString(),
          dncChannel: "quick_reply_button",
        };
        if (sc.normalizedCandidateId && msgBefore.jobId) {
          // Candidate clicked the one-click "don't contact me" reply link → candidate actor.
          await changeCandidateStage({
            tenantId: msgBefore.tenantId ?? (sc as any).tenantId ?? "",
            candidateId: sc.normalizedCandidateId,
            jobId: msgBefore.jobId,
            to: "rejected",
            actor: { type: "candidate", role: "candidate", id: sc.normalizedCandidateId },
            source: "quick_reply",
            reason: "Do not contact (candidate request)",
            sourcedId: sc.id,
            sourcedRawDataPatch: dncRawPatch,
            metadata: { action: "dnc", messageId },
          });
        } else {
          // stage-write-exempt: sourced row has no canonical candidateId to key the STAGE_CHANGED event/audit rows
          await db.update(sourcedCandidatesTable).set({
            rawData: { ...raw, stage: "rejected", ...dncRawPatch },
          }).where(eq(sourcedCandidatesTable.id, sc.id));
        }
      }
      const alreadyAuditedDnc = sc
        ? (await db.select({ id: candidateRejectionsTable.id })
            .from(candidateRejectionsTable)
            .where(and(
              eq(candidateRejectionsTable.sourcedId, sc.id),
              eq(candidateRejectionsTable.jobId, msgBefore.jobId),
            )).limit(1)).length > 0
        : false;
      if (!alreadyAuditedDnc) {
        try {
          await recordRejection({
            tenantId: msgBefore.tenantId,
            jobId: msgBefore.jobId,
            sourcedId: sc?.id ?? null,
            candidateId: sc?.normalizedCandidateId ?? cand?.id ?? null,
            rejectedByRole: "system",
            reason: "Do not contact (candidate request)",
            notes: "Candidate clicked \"Don't contact me\" reply button — global DNC applied.",
            fromStage: (sc?.rawData as any)?.stage ?? null,
            sendEmail: false,
          });
        } catch (err: any) {
          logger.error({ err: err?.message, messageId }, "[quick-reply-msg] recordRejection (DNC) failed");
        }
      }
      if (!dncOk) {
        logger.warn({ messageId, email: candEmail },
          "[quick-reply-msg] DNC clicked but no candidate row was updated");
      }
      title = "You've been unsubscribed";
      message = "We've removed you from all outreach across the platform. You won't hear from us again. Sorry for the noise.";
      color = "#991b1b";
    }

    // Notify the assigned recruiter — both an in-app inbox row AND an
    // email (or digest entry, depending on their preference). Without
    // this, candidates clicking quick-reply buttons would silently apply
    // side effects without ever surfacing to the recruiter.
    try {
      // Always notify — the candidate received an outreach email by
      // definition, so we should always have an email to attribute the
      // reply to. If somehow we don't, the helper still writes the
      // in-app inbox row with an empty `From` rather than dropping the
      // notification entirely.
      const candEmail = cand?.email ?? (sc?.rawData as any)?.email ?? "";
      const candName = cand
        ? `${cand.firstName ?? ""} ${cand.lastName ?? ""}`.trim() || null
        : (sc?.rawData as any)?.name ?? null;
      await notifyRecruiterOfReply({
        tenantId: msgBefore.tenantId,
        jobId: msgBefore.jobId,
        candidateId: cand?.id ?? sc?.normalizedCandidateId ?? sc?.id ?? msgBefore.candidateId,
        candidateName: candName,
        candidateEmail: candEmail,
        classification: QUICK_REPLY_TO_CLASSIFICATION[action],
        body: QUICK_REPLY_BODY[action],
        campaignId: null,
      });
    } catch (err: any) {
      logger.error({ err: err?.message, messageId, action },
        "[quick-reply-msg] notifyRecruiterOfReply failed");
    }

    void recordAudit({
      tenantId: msgBefore.tenantId,
      actorType: "candidate",
      actorId: sc?.id ?? cand?.id ?? null,
      actorLabel: cand?.email ?? (sc?.rawData as any)?.email ?? "candidate",
      subjectType: "candidate",
      subjectId: sc?.id ?? cand?.id ?? null,
      subjectLabel: cand?.email ?? (sc?.rawData as any)?.email ?? "candidate",
      channel: "email",
      direction: "inbound",
      action: `outreach.quick_reply.${action}`,
      title: `Candidate quick-reply: ${action}`,
      metadata: { messageId, jobId: msgBefore.jobId, source: "orchestrator" },
    });

    res.status(200).type("html").send(renderResult(title, message, color));
  } catch (err: any) {
    logger.error({ err: err?.message, messageId, action }, "[quick-reply-msg] handler failed");
    res.status(500).type("html").send(renderError(
      "Something went wrong",
      "We couldn't fully record your response. Please reply to the original email so we don't miss it.",
    ));
  }
});

function renderConfirmMsg(token: string, action: ReplyAction): string {
  const c = ACTION_COPY[action];
  return baseLayout(c.title, c.color, `
    <p style="margin:0 0 22px;font-size:15px;line-height:1.55;color:#4b5563;">${esc(c.body)}</p>
    <form method="POST" action="/api/outreach/reply-msg/${esc(token)}" style="margin:0;">
      <button type="submit" style="display:inline-block;padding:12px 22px;border:0;border-radius:24px;font:500 15px/1 -apple-system,Segoe UI,Helvetica,Arial,sans-serif;color:#fff;background:${c.color};cursor:pointer;">${esc(c.cta)}</button>
    </form>
    <div style="margin-top:18px;font-size:12px;color:#9ca3af;">Not you? Just close this page — nothing has been changed yet.</div>
  `);
}

// ── HTML helpers ────────────────────────────────────────────────────────────

const ACTION_COPY: Record<ReplyAction, { title: string; body: string; cta: string; color: string }> = {
  interested: {
    title: "Confirm: you're interested",
    body: "Click the button below and we'll send you an interview invite right away.",
    cta: "Yes, I'm interested",
    color: "#0f6f3a",
  },
  not_interested_job: {
    title: "Confirm: skip this role",
    body: "We'll stop emailing you about this role. You'll still hear about other roles that might be a fit.",
    cta: "Skip this role",
    color: "#7c4a03",
  },
  dnc: {
    title: "Confirm: stop all emails",
    body: "We'll remove you from every outreach on the platform. This affects all current and future jobs across all recruiters.",
    cta: "Stop all emails",
    color: "#991b1b",
  },
};

function renderConfirm(token: string, action: ReplyAction): string {
  const c = ACTION_COPY[action];
  return baseLayout(c.title, c.color, `
    <p style="margin:0 0 22px;font-size:15px;line-height:1.55;color:#4b5563;">${esc(c.body)}</p>
    <form method="POST" action="/api/outreach/reply/${esc(token)}" style="margin:0;">
      <button type="submit" style="display:inline-block;padding:12px 22px;border:0;border-radius:24px;font:500 15px/1 -apple-system,Segoe UI,Helvetica,Arial,sans-serif;color:#fff;background:${c.color};cursor:pointer;">${esc(c.cta)}</button>
    </form>
    <div style="margin-top:18px;font-size:12px;color:#9ca3af;">Not you? Just close this page — nothing has been changed yet.</div>
  `);
}

function renderResult(title: string, message: string, color: string): string {
  return baseLayout(title, color, `<p style="margin:0;font-size:15px;line-height:1.55;color:#4b5563;">${esc(message)}</p>`);
}

function renderError(title: string, message: string): string {
  return baseLayout(title, "#991b1b", `<p style="margin:0;font-size:15px;line-height:1.55;color:#4b5563;">${esc(message)}</p>`);
}

function baseLayout(title: string, accent: string, inner: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)}</title>
<style>
  body{margin:0;font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif;background:#f9fafb;color:#1f2937;display:flex;align-items:center;justify-content:center;min-height:100vh;padding:24px;}
  .card{max-width:480px;width:100%;background:#fff;border-radius:14px;padding:36px 32px;box-shadow:0 4px 24px rgba(0,0,0,.06);text-align:center;box-sizing:border-box;}
  .bar{width:48px;height:4px;border-radius:2px;background:${accent};margin:0 auto 22px;}
  h1{margin:0 0 14px;font-size:22px;color:${accent};}
  .foot{margin-top:24px;font-size:12px;color:#9ca3af;}
</style></head>
<body><div class="card"><div class="bar"></div><h1>${esc(title)}</h1>${inner}<div class="foot">Lexy · AI Hiring Platform</div></div></body></html>`;
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export default router;
