/**
 * countries-data.ts — Static country / currency / state / city reference data.
 *
 * ── What this file does ───────────────────────────────────────────────────────
 * Exports a COUNTRIES constant — an array of ~50 countries each carrying:
 *   name      Human-readable country name
 *   code      ISO 3166-1 alpha-2 code (e.g. "AE", "GB")
 *   currency  { code, symbol, name } — local currency for salary display
 *   cities    Flat list of top cities (kept for backward-compat with consumers
 *             that don't care about states; equals the union of all state
 *             cities for countries that have a `states` array).
 *   states    Optional structured list of states/provinces (or the locally
 *             appropriate top-level admin division: prefecture, governorate,
 *             oblast, region, etc.) with their cities. Present for every
 *             country that has meaningful subdivisions — currently all
 *             countries in the list except city-state-sized jurisdictions
 *             (Singapore, Hong Kong), where it is intentionally omitted.
 *             When undefined, UIs should disable the State picker (or show
 *             a "Not applicable" hint) and let the user pick a city directly.
 *
 * This file has no runtime dependencies — it is purely static data used by
 * form fields that need country / state / city selection.
 *
 * ── Used by ───────────────────────────────────────────────────────────────────
 *  pages/recruiter/jobs/index.tsx         Job creation — location fields
 *  pages/portal/profile.tsx               Candidate location picker
 *  components/candidates/CsvImportDialog  Location normalisation hints
 */

export interface StateData {
  /** Full state / province name as displayed in the UI. */
  name: string;
  /** ISO 3166-2 sub-code without the country prefix (e.g. "CA" for California). */
  code: string;
  cities: string[];
}

export interface CountryData {
  name: string;
  code: string;
  currency: { code: string; symbol: string; name: string };
  cities: string[];
  states?: StateData[];
}

export const COUNTRIES: CountryData[] = [
  { name: "Argentina", code: "AR", currency: { code: "ARS", symbol: "$", name: "Argentine Peso" }, cities: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "Tucumán", "La Plata", "Mar del Plata", "Salta", "Santa Fe", "San Juan"], states: [
    { name: "Buenos Aires (City)",   code: "C", cities: ["Buenos Aires"] },
    { name: "Buenos Aires Province", code: "B", cities: ["La Plata", "Mar del Plata"] },
    { name: "Córdoba",               code: "X", cities: ["Córdoba"] },
    { name: "Santa Fe",              code: "S", cities: ["Rosario", "Santa Fe"] },
    { name: "Mendoza",               code: "M", cities: ["Mendoza"] },
    { name: "Tucumán",               code: "T", cities: ["Tucumán"] },
    { name: "Salta",                 code: "A", cities: ["Salta"] },
    { name: "San Juan",              code: "J", cities: ["San Juan"] },
  ] },
  { name: "Australia", code: "AU", currency: { code: "AUD", symbol: "A$", name: "Australian Dollar" }, cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Canberra", "Newcastle", "Hobart", "Darwin"], states: [
    { name: "New South Wales",                code: "NSW", cities: ["Sydney", "Newcastle"] },
    { name: "Victoria",                       code: "VIC", cities: ["Melbourne"] },
    { name: "Queensland",                     code: "QLD", cities: ["Brisbane", "Gold Coast"] },
    { name: "Western Australia",              code: "WA",  cities: ["Perth"] },
    { name: "South Australia",                code: "SA",  cities: ["Adelaide"] },
    { name: "Australian Capital Territory",   code: "ACT", cities: ["Canberra"] },
    { name: "Tasmania",                       code: "TAS", cities: ["Hobart"] },
    { name: "Northern Territory",             code: "NT",  cities: ["Darwin"] },
  ] },
  { name: "Austria", code: "AT", currency: { code: "EUR", symbol: "€", name: "Euro" }, cities: ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "St. Pölten", "Dornbirn"], states: [
    { name: "Vienna",        code: "9", cities: ["Vienna"] },
    { name: "Styria",        code: "6", cities: ["Graz"] },
    { name: "Upper Austria", code: "4", cities: ["Linz", "Wels"] },
    { name: "Salzburg",      code: "5", cities: ["Salzburg"] },
    { name: "Tyrol",         code: "7", cities: ["Innsbruck"] },
    { name: "Carinthia",     code: "2", cities: ["Klagenfurt", "Villach"] },
    { name: "Lower Austria", code: "3", cities: ["St. Pölten"] },
    { name: "Vorarlberg",    code: "8", cities: ["Dornbirn"] },
  ] },
  { name: "Belgium", code: "BE", currency: { code: "EUR", symbol: "€", name: "Euro" }, cities: ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Namur", "Leuven", "Mons", "Aalst"], states: [
    { name: "Brussels-Capital", code: "BRU", cities: ["Brussels"] },
    { name: "Antwerp",          code: "VAN", cities: ["Antwerp"] },
    { name: "East Flanders",    code: "VOV", cities: ["Ghent", "Aalst"] },
    { name: "Hainaut",          code: "WHT", cities: ["Charleroi", "Mons"] },
    { name: "Liège",            code: "WLG", cities: ["Liège"] },
    { name: "West Flanders",    code: "VWV", cities: ["Bruges"] },
    { name: "Namur",            code: "WNA", cities: ["Namur"] },
    { name: "Flemish Brabant",  code: "VBR", cities: ["Leuven"] },
  ] },
  { name: "Brazil", code: "BR", currency: { code: "BRL", symbol: "R$", name: "Brazilian Real" }, cities: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre", "Goiânia", "Belém", "Florianópolis"], states: [
    { name: "São Paulo",         code: "SP", cities: ["São Paulo"] },
    { name: "Rio de Janeiro",    code: "RJ", cities: ["Rio de Janeiro"] },
    { name: "Distrito Federal",  code: "DF", cities: ["Brasília"] },
    { name: "Bahia",             code: "BA", cities: ["Salvador"] },
    { name: "Ceará",             code: "CE", cities: ["Fortaleza"] },
    { name: "Minas Gerais",      code: "MG", cities: ["Belo Horizonte"] },
    { name: "Amazonas",          code: "AM", cities: ["Manaus"] },
    { name: "Paraná",            code: "PR", cities: ["Curitiba"] },
    { name: "Pernambuco",        code: "PE", cities: ["Recife"] },
    { name: "Rio Grande do Sul", code: "RS", cities: ["Porto Alegre"] },
    { name: "Goiás",             code: "GO", cities: ["Goiânia"] },
    { name: "Pará",              code: "PA", cities: ["Belém"] },
    { name: "Santa Catarina",    code: "SC", cities: ["Florianópolis"] },
  ] },
  { name: "Canada", code: "CA", currency: { code: "CAD", symbol: "C$", name: "Canadian Dollar" }, cities: ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Kitchener", "London", "Halifax", "Victoria", "Saskatoon", "Regina"], states: [
    { name: "Ontario",          code: "ON", cities: ["Toronto", "Ottawa", "Hamilton", "Kitchener", "London"] },
    { name: "Quebec",           code: "QC", cities: ["Montreal", "Quebec City"] },
    { name: "British Columbia", code: "BC", cities: ["Vancouver", "Victoria"] },
    { name: "Alberta",          code: "AB", cities: ["Calgary", "Edmonton"] },
    { name: "Manitoba",         code: "MB", cities: ["Winnipeg"] },
    { name: "Nova Scotia",      code: "NS", cities: ["Halifax"] },
    { name: "Saskatchewan",     code: "SK", cities: ["Saskatoon", "Regina"] },
  ] },
  { name: "Chile", code: "CL", currency: { code: "CLP", symbol: "$", name: "Chilean Peso" }, cities: ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Talca", "Arica", "Iquique"], states: [
    { name: "Santiago Metropolitan", code: "RM",  cities: ["Santiago"] },
    { name: "Valparaíso",            code: "VS",  cities: ["Valparaíso"] },
    { name: "Biobío",                code: "BI",  cities: ["Concepción"] },
    { name: "Coquimbo",              code: "CO",  cities: ["La Serena"] },
    { name: "Antofagasta",           code: "AN",  cities: ["Antofagasta"] },
    { name: "La Araucanía",          code: "AR",  cities: ["Temuco"] },
    { name: "O'Higgins",             code: "LI",  cities: ["Rancagua"] },
    { name: "Maule",                 code: "ML",  cities: ["Talca"] },
    { name: "Arica y Parinacota",    code: "AP",  cities: ["Arica"] },
    { name: "Tarapacá",              code: "TA",  cities: ["Iquique"] },
  ] },
  { name: "China", code: "CN", currency: { code: "CNY", symbol: "¥", name: "Chinese Yuan" }, cities: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Hangzhou", "Wuhan", "Xi'an", "Nanjing", "Tianjin", "Chongqing", "Suzhou", "Qingdao", "Zhengzhou", "Dongguan", "Shenyang"], states: [
    { name: "Beijing",   code: "BJ", cities: ["Beijing"] },
    { name: "Shanghai",  code: "SH", cities: ["Shanghai"] },
    { name: "Guangdong", code: "GD", cities: ["Guangzhou", "Shenzhen", "Dongguan"] },
    { name: "Sichuan",   code: "SC", cities: ["Chengdu"] },
    { name: "Zhejiang",  code: "ZJ", cities: ["Hangzhou"] },
    { name: "Hubei",     code: "HB", cities: ["Wuhan"] },
    { name: "Shaanxi",   code: "SN", cities: ["Xi'an"] },
    { name: "Jiangsu",   code: "JS", cities: ["Nanjing", "Suzhou"] },
    { name: "Tianjin",   code: "TJ", cities: ["Tianjin"] },
    { name: "Chongqing", code: "CQ", cities: ["Chongqing"] },
    { name: "Shandong",  code: "SD", cities: ["Qingdao"] },
    { name: "Henan",     code: "HA", cities: ["Zhengzhou"] },
    { name: "Liaoning",  code: "LN", cities: ["Shenyang"] },
  ] },
  { name: "Colombia", code: "CO", currency: { code: "COP", symbol: "$", name: "Colombian Peso" }, cities: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga", "Pereira", "Manizales", "Ibagué"], states: [
    { name: "Bogotá D.C.",         code: "DC", cities: ["Bogotá"] },
    { name: "Antioquia",           code: "ANT", cities: ["Medellín"] },
    { name: "Valle del Cauca",     code: "VAC", cities: ["Cali"] },
    { name: "Atlántico",           code: "ATL", cities: ["Barranquilla"] },
    { name: "Bolívar",             code: "BOL", cities: ["Cartagena"] },
    { name: "Norte de Santander",  code: "NSA", cities: ["Cúcuta"] },
    { name: "Santander",           code: "SAN", cities: ["Bucaramanga"] },
    { name: "Risaralda",           code: "RIS", cities: ["Pereira"] },
    { name: "Caldas",              code: "CAL", cities: ["Manizales"] },
    { name: "Tolima",              code: "TOL", cities: ["Ibagué"] },
  ] },
  { name: "Czech Republic", code: "CZ", currency: { code: "CZK", symbol: "Kč", name: "Czech Koruna" }, cities: ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc", "Ústí nad Labem", "Hradec Králové", "České Budějovice", "Pardubice"], states: [
    { name: "Prague",            code: "PR", cities: ["Prague"] },
    { name: "South Moravian",    code: "JM", cities: ["Brno"] },
    { name: "Moravian-Silesian", code: "MS", cities: ["Ostrava"] },
    { name: "Plzeň",             code: "PL", cities: ["Plzeň"] },
    { name: "Liberec",           code: "LI", cities: ["Liberec"] },
    { name: "Olomouc",           code: "OL", cities: ["Olomouc"] },
    { name: "Ústí nad Labem",    code: "US", cities: ["Ústí nad Labem"] },
    { name: "Hradec Králové",    code: "HK", cities: ["Hradec Králové"] },
    { name: "South Bohemian",    code: "JC", cities: ["České Budějovice"] },
    { name: "Pardubice",         code: "PA", cities: ["Pardubice"] },
  ] },
  { name: "Denmark", code: "DK", currency: { code: "DKK", symbol: "kr", name: "Danish Krone" }, cities: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Horsens", "Vejle", "Roskilde"], states: [
    { name: "Capital Region",   code: "84", cities: ["Copenhagen", "Roskilde"] },
    { name: "Central Denmark",  code: "82", cities: ["Aarhus", "Randers", "Horsens"] },
    { name: "Southern Denmark", code: "83", cities: ["Odense", "Esbjerg", "Kolding", "Vejle"] },
    { name: "North Denmark",    code: "81", cities: ["Aalborg"] },
  ] },
  { name: "Egypt", code: "EG", currency: { code: "EGP", symbol: "£", name: "Egyptian Pound" }, cities: ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said", "Suez", "Luxor", "Mansoura", "Tanta", "Asyut"], states: [
    { name: "Cairo",      code: "C",   cities: ["Cairo"] },
    { name: "Alexandria", code: "ALX", cities: ["Alexandria"] },
    { name: "Giza",       code: "GZ",  cities: ["Giza"] },
    { name: "Qalyubia",   code: "KB",  cities: ["Shubra El Kheima"] },
    { name: "Port Said",  code: "PTS", cities: ["Port Said"] },
    { name: "Suez",       code: "SUZ", cities: ["Suez"] },
    { name: "Luxor",      code: "LX",  cities: ["Luxor"] },
    { name: "Dakahlia",   code: "DK",  cities: ["Mansoura"] },
    { name: "Gharbia",    code: "GH",  cities: ["Tanta"] },
    { name: "Asyut",      code: "AST", cities: ["Asyut"] },
  ] },
  { name: "Finland", code: "FI", currency: { code: "EUR", symbol: "€", name: "Euro" }, cities: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Lahti", "Kuopio", "Pori"], states: [
    { name: "Uusimaa",            code: "18", cities: ["Helsinki", "Espoo", "Vantaa"] },
    { name: "Pirkanmaa",          code: "11", cities: ["Tampere"] },
    { name: "North Ostrobothnia", code: "14", cities: ["Oulu"] },
    { name: "Southwest Finland",  code: "19", cities: ["Turku"] },
    { name: "Central Finland",    code: "12", cities: ["Jyväskylä"] },
    { name: "Päijänne Tavastia",  code: "16", cities: ["Lahti"] },
    { name: "North Savo",         code: "15", cities: ["Kuopio"] },
    { name: "Satakunta",          code: "17", cities: ["Pori"] },
  ] },
  { name: "France", code: "FR", currency: { code: "EUR", symbol: "€", name: "Euro" }, cities: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims", "Saint-Étienne", "Toulon", "Le Havre"], states: [
    { name: "Île-de-France",                code: "IDF", cities: ["Paris"] },
    { name: "Provence-Alpes-Côte d'Azur",   code: "PAC", cities: ["Marseille", "Nice", "Toulon"] },
    { name: "Auvergne-Rhône-Alpes",         code: "ARA", cities: ["Lyon", "Saint-Étienne"] },
    { name: "Occitanie",                    code: "OCC", cities: ["Toulouse", "Montpellier"] },
    { name: "Pays de la Loire",             code: "PDL", cities: ["Nantes"] },
    { name: "Grand Est",                    code: "GES", cities: ["Strasbourg", "Reims"] },
    { name: "Nouvelle-Aquitaine",           code: "NAQ", cities: ["Bordeaux"] },
    { name: "Hauts-de-France",              code: "HDF", cities: ["Lille"] },
    { name: "Bretagne",                     code: "BRE", cities: ["Rennes"] },
    { name: "Normandie",                    code: "NOR", cities: ["Le Havre"] },
  ] },
  { name: "Germany", code: "DE", currency: { code: "EUR", symbol: "€", name: "Euro" }, cities: ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden", "Hanover", "Nuremberg", "Duisburg"], states: [
    { name: "Berlin",                  code: "BE", cities: ["Berlin"] },
    { name: "Hamburg",                 code: "HH", cities: ["Hamburg"] },
    { name: "Bavaria",                 code: "BY", cities: ["Munich", "Nuremberg"] },
    { name: "North Rhine-Westphalia",  code: "NW", cities: ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Duisburg"] },
    { name: "Hesse",                   code: "HE", cities: ["Frankfurt"] },
    { name: "Baden-Württemberg",       code: "BW", cities: ["Stuttgart"] },
    { name: "Saxony",                  code: "SN", cities: ["Leipzig", "Dresden"] },
    { name: "Bremen",                  code: "HB", cities: ["Bremen"] },
    { name: "Lower Saxony",            code: "NI", cities: ["Hanover"] },
  ] },
  { name: "Greece", code: "GR", currency: { code: "EUR", symbol: "€", name: "Euro" }, cities: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos", "Rhodes", "Ioannina", "Chania", "Agrinio"], states: [
    { name: "Attica",             code: "I", cities: ["Athens"] },
    { name: "Central Macedonia",  code: "B", cities: ["Thessaloniki"] },
    { name: "Western Greece",     code: "G", cities: ["Patras", "Agrinio"] },
    { name: "Crete",              code: "M", cities: ["Heraklion", "Chania"] },
    { name: "Thessaly",           code: "E", cities: ["Larissa", "Volos"] },
    { name: "South Aegean",       code: "L", cities: ["Rhodes"] },
    { name: "Epirus",             code: "D", cities: ["Ioannina"] },
  ] },
  // Hong Kong is treated as a single jurisdiction — no states picker shown.
  { name: "Hong Kong", code: "HK", currency: { code: "HKD", symbol: "HK$", name: "Hong Kong Dollar" }, cities: ["Hong Kong Island", "Kowloon", "New Territories", "Lantau Island", "Tsuen Wan", "Sha Tin", "Tuen Mun", "Yuen Long"] },
  { name: "Hungary", code: "HU", currency: { code: "HUF", symbol: "Ft", name: "Hungarian Forint" }, cities: ["Budapest", "Debrecen", "Miskolc", "Szeged", "Pécs", "Győr", "Nyíregyháza", "Kecskemét", "Székesfehérvár", "Szombathely"], states: [
    { name: "Budapest",                  code: "BU", cities: ["Budapest"] },
    { name: "Hajdú-Bihar",               code: "HB", cities: ["Debrecen"] },
    { name: "Borsod-Abaúj-Zemplén",      code: "BZ", cities: ["Miskolc"] },
    { name: "Csongrád-Csanád",           code: "CS", cities: ["Szeged"] },
    { name: "Baranya",                   code: "BA", cities: ["Pécs"] },
    { name: "Győr-Moson-Sopron",         code: "GS", cities: ["Győr"] },
    { name: "Szabolcs-Szatmár-Bereg",    code: "SZ", cities: ["Nyíregyháza"] },
    { name: "Bács-Kiskun",               code: "BK", cities: ["Kecskemét"] },
    { name: "Fejér",                     code: "FE", cities: ["Székesfehérvár"] },
    { name: "Vas",                       code: "VA", cities: ["Szombathely"] },
  ] },
  { name: "India", code: "IN", currency: { code: "INR", symbol: "₹", name: "Indian Rupee" }, cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Surat", "Lucknow", "Kanpur", "Nagpur", "Indore", "Bhopal", "Visakhapatnam", "Patna", "Vadodara", "Gurgaon", "Noida"], states: [
    { name: "Maharashtra",     code: "MH", cities: ["Mumbai", "Pune", "Nagpur"] },
    { name: "Delhi",           code: "DL", cities: ["Delhi"] },
    { name: "Karnataka",       code: "KA", cities: ["Bangalore"] },
    { name: "Telangana",       code: "TS", cities: ["Hyderabad"] },
    { name: "Tamil Nadu",      code: "TN", cities: ["Chennai"] },
    { name: "West Bengal",     code: "WB", cities: ["Kolkata"] },
    { name: "Gujarat",         code: "GJ", cities: ["Ahmedabad", "Surat", "Vadodara"] },
    { name: "Rajasthan",       code: "RJ", cities: ["Jaipur"] },
    { name: "Uttar Pradesh",   code: "UP", cities: ["Lucknow", "Kanpur", "Noida"] },
    { name: "Madhya Pradesh",  code: "MP", cities: ["Indore", "Bhopal"] },
    { name: "Andhra Pradesh",  code: "AP", cities: ["Visakhapatnam"] },
    { name: "Bihar",           code: "BR", cities: ["Patna"] },
    { name: "Haryana",         code: "HR", cities: ["Gurgaon"] },
  ] },
  { name: "Indonesia", code: "ID", currency: { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" }, cities: ["Jakarta", "Surabaya", "Medan", "Bandung", "Bekasi", "Tangerang", "Depok", "Semarang", "Palembang", "Makassar", "Bali", "Yogyakarta"], states: [
    { name: "Jakarta",                       code: "JK", cities: ["Jakarta"] },
    { name: "East Java",                     code: "JI", cities: ["Surabaya"] },
    { name: "North Sumatra",                 code: "SU", cities: ["Medan"] },
    { name: "West Java",                     code: "JB", cities: ["Bandung", "Bekasi", "Depok"] },
    { name: "Banten",                        code: "BT", cities: ["Tangerang"] },
    { name: "Central Java",                  code: "JT", cities: ["Semarang"] },
    { name: "South Sumatra",                 code: "SS", cities: ["Palembang"] },
    { name: "South Sulawesi",                code: "SN", cities: ["Makassar"] },
    { name: "Bali",                          code: "BA", cities: ["Bali"] },
    { name: "Special Region of Yogyakarta",  code: "YO", cities: ["Yogyakarta"] },
  ] },
  { name: "Ireland", code: "IE", currency: { code: "EUR", symbol: "€", name: "Euro" }, cities: ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Dundalk", "Swords", "Bray", "Navan"], states: [
    { name: "Leinster",  code: "L", cities: ["Dublin", "Drogheda", "Dundalk", "Swords", "Bray", "Navan", "Waterford"] },
    { name: "Munster",   code: "M", cities: ["Cork", "Limerick"] },
    { name: "Connacht",  code: "C", cities: ["Galway"] },
  ] },
  { name: "Israel", code: "IL", currency: { code: "ILS", symbol: "₪", name: "Israeli Shekel" }, cities: ["Tel Aviv", "Jerusalem", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Netanya", "Beer Sheva", "Bnei Brak", "Holon"], states: [
    { name: "Tel Aviv",   code: "TA", cities: ["Tel Aviv", "Holon", "Bnei Brak"] },
    { name: "Jerusalem",  code: "JM", cities: ["Jerusalem"] },
    { name: "Haifa",      code: "HA", cities: ["Haifa"] },
    { name: "Central",    code: "M",  cities: ["Rishon LeZion", "Petah Tikva", "Netanya"] },
    { name: "Southern",   code: "D",  cities: ["Ashdod", "Beer Sheva"] },
  ] },
  { name: "Italy", code: "IT", currency: { code: "EUR", symbol: "€", name: "Euro" }, cities: ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania", "Venice", "Verona", "Messina", "Padua", "Trieste"], states: [
    { name: "Lazio",                  code: "62", cities: ["Rome"] },
    { name: "Lombardy",               code: "25", cities: ["Milan"] },
    { name: "Campania",               code: "72", cities: ["Naples"] },
    { name: "Piedmont",               code: "21", cities: ["Turin"] },
    { name: "Sicily",                 code: "82", cities: ["Palermo", "Catania", "Messina"] },
    { name: "Liguria",                code: "42", cities: ["Genoa"] },
    { name: "Emilia-Romagna",         code: "45", cities: ["Bologna"] },
    { name: "Tuscany",                code: "52", cities: ["Florence"] },
    { name: "Apulia",                 code: "75", cities: ["Bari"] },
    { name: "Veneto",                 code: "34", cities: ["Venice", "Verona", "Padua"] },
    { name: "Friuli Venezia Giulia",  code: "36", cities: ["Trieste"] },
  ] },
  { name: "Japan", code: "JP", currency: { code: "JPY", symbol: "¥", name: "Japanese Yen" }, cities: ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kawasaki", "Kobe", "Kyoto", "Saitama", "Hiroshima", "Sendai", "Chiba", "Kitakyushu", "Sagamihara"], states: [
    { name: "Tokyo",      code: "13", cities: ["Tokyo"] },
    { name: "Kanagawa",   code: "14", cities: ["Yokohama", "Kawasaki", "Sagamihara"] },
    { name: "Osaka",      code: "27", cities: ["Osaka"] },
    { name: "Aichi",      code: "23", cities: ["Nagoya"] },
    { name: "Hokkaido",   code: "01", cities: ["Sapporo"] },
    { name: "Fukuoka",    code: "40", cities: ["Fukuoka", "Kitakyushu"] },
    { name: "Hyogo",      code: "28", cities: ["Kobe"] },
    { name: "Kyoto",      code: "26", cities: ["Kyoto"] },
    { name: "Saitama",    code: "11", cities: ["Saitama"] },
    { name: "Hiroshima",  code: "34", cities: ["Hiroshima"] },
    { name: "Miyagi",     code: "04", cities: ["Sendai"] },
    { name: "Chiba",      code: "12", cities: ["Chiba"] },
  ] },
  { name: "Kenya", code: "KE", currency: { code: "KES", symbol: "KSh", name: "Kenyan Shilling" }, cities: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika", "Malindi", "Kitale", "Garissa", "Kakamega"], states: [
    { name: "Nairobi",      code: "30", cities: ["Nairobi"] },
    { name: "Mombasa",      code: "28", cities: ["Mombasa"] },
    { name: "Kisumu",       code: "11", cities: ["Kisumu"] },
    { name: "Nakuru",       code: "31", cities: ["Nakuru"] },
    { name: "Uasin Gishu",  code: "39", cities: ["Eldoret"] },
    { name: "Kiambu",       code: "08", cities: ["Thika"] },
    { name: "Kilifi",       code: "09", cities: ["Malindi"] },
    { name: "Trans-Nzoia",  code: "37", cities: ["Kitale"] },
    { name: "Garissa",      code: "03", cities: ["Garissa"] },
    { name: "Kakamega",     code: "05", cities: ["Kakamega"] },
  ] },
  { name: "Malaysia", code: "MY", currency: { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" }, cities: ["Kuala Lumpur", "Petaling Jaya", "Klang", "Ipoh", "Shah Alam", "Penang", "Johor Bahru", "Malacca", "Kota Kinabalu", "Kuching"], states: [
    { name: "Kuala Lumpur", code: "14", cities: ["Kuala Lumpur"] },
    { name: "Selangor",     code: "10", cities: ["Petaling Jaya", "Klang", "Shah Alam"] },
    { name: "Perak",        code: "08", cities: ["Ipoh"] },
    { name: "Penang",       code: "07", cities: ["Penang"] },
    { name: "Johor",        code: "01", cities: ["Johor Bahru"] },
    { name: "Malacca",      code: "04", cities: ["Malacca"] },
    { name: "Sabah",        code: "12", cities: ["Kota Kinabalu"] },
    { name: "Sarawak",      code: "13", cities: ["Kuching"] },
  ] },
  { name: "Mexico", code: "MX", currency: { code: "MXN", symbol: "$", name: "Mexican Peso" }, cities: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Juárez", "Torreón", "Querétaro", "Mérida", "San Luis Potosí", "Aguascalientes", "Cancún", "Culiacán", "Chihuahua"], states: [
    { name: "Mexico City",       code: "CDMX", cities: ["Mexico City"] },
    { name: "Jalisco",           code: "JAL",  cities: ["Guadalajara"] },
    { name: "Nuevo León",        code: "NL",   cities: ["Monterrey"] },
    { name: "Puebla",            code: "PUE",  cities: ["Puebla"] },
    { name: "Baja California",   code: "BC",   cities: ["Tijuana"] },
    { name: "Guanajuato",        code: "GTO",  cities: ["León"] },
    { name: "Chihuahua",         code: "CHH",  cities: ["Juárez", "Chihuahua"] },
    { name: "Coahuila",          code: "COA",  cities: ["Torreón"] },
    { name: "Querétaro",         code: "QRO",  cities: ["Querétaro"] },
    { name: "Yucatán",           code: "YUC",  cities: ["Mérida"] },
    { name: "San Luis Potosí",   code: "SLP",  cities: ["San Luis Potosí"] },
    { name: "Aguascalientes",    code: "AGU",  cities: ["Aguascalientes"] },
    { name: "Quintana Roo",      code: "ROO",  cities: ["Cancún"] },
    { name: "Sinaloa",           code: "SIN",  cities: ["Culiacán"] },
  ] },
  { name: "Netherlands", code: "NL", currency: { code: "EUR", symbol: "€", name: "Euro" }, cities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Groningen", "Tilburg", "Almere", "Breda", "Nijmegen"], states: [
    { name: "North Holland", code: "NH", cities: ["Amsterdam"] },
    { name: "South Holland", code: "ZH", cities: ["Rotterdam", "The Hague"] },
    { name: "Utrecht",       code: "UT", cities: ["Utrecht"] },
    { name: "North Brabant", code: "NB", cities: ["Eindhoven", "Tilburg", "Breda"] },
    { name: "Groningen",     code: "GR", cities: ["Groningen"] },
    { name: "Flevoland",     code: "FL", cities: ["Almere"] },
    { name: "Gelderland",    code: "GE", cities: ["Nijmegen"] },
  ] },
  { name: "New Zealand", code: "NZ", currency: { code: "NZD", symbol: "NZ$", name: "New Zealand Dollar" }, cities: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Napier-Hastings", "Dunedin", "Palmerston North", "Nelson", "Rotorua"], states: [
    { name: "Auckland",            code: "AUK", cities: ["Auckland"] },
    { name: "Wellington",          code: "WGN", cities: ["Wellington"] },
    { name: "Canterbury",          code: "CAN", cities: ["Christchurch"] },
    { name: "Waikato",             code: "WKO", cities: ["Hamilton"] },
    { name: "Bay of Plenty",       code: "BOP", cities: ["Tauranga", "Rotorua"] },
    { name: "Hawke's Bay",         code: "HKB", cities: ["Napier-Hastings"] },
    { name: "Otago",               code: "OTA", cities: ["Dunedin"] },
    { name: "Manawatū-Whanganui",  code: "MWT", cities: ["Palmerston North"] },
    { name: "Nelson",              code: "NSN", cities: ["Nelson"] },
  ] },
  { name: "Nigeria", code: "NG", currency: { code: "NGN", symbol: "₦", name: "Nigerian Naira" }, cities: ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt", "Benin City", "Maiduguri", "Zaria", "Aba", "Jos", "Kaduna", "Enugu"], states: [
    { name: "Lagos",                       code: "LA", cities: ["Lagos"] },
    { name: "Federal Capital Territory",   code: "FC", cities: ["Abuja"] },
    { name: "Kano",                        code: "KN", cities: ["Kano"] },
    { name: "Oyo",                         code: "OY", cities: ["Ibadan"] },
    { name: "Rivers",                      code: "RI", cities: ["Port Harcourt"] },
    { name: "Edo",                         code: "ED", cities: ["Benin City"] },
    { name: "Borno",                       code: "BO", cities: ["Maiduguri"] },
    { name: "Kaduna",                      code: "KD", cities: ["Zaria", "Kaduna"] },
    { name: "Abia",                        code: "AB", cities: ["Aba"] },
    { name: "Plateau",                     code: "PL", cities: ["Jos"] },
    { name: "Enugu",                       code: "EN", cities: ["Enugu"] },
  ] },
  { name: "Norway", code: "NO", currency: { code: "NOK", symbol: "kr", name: "Norwegian Krone" }, cities: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Fredrikstad", "Kristiansand", "Sandnes", "Tromsø", "Sarpsborg"], states: [
    { name: "Oslo",                  code: "03", cities: ["Oslo"] },
    { name: "Vestland",              code: "46", cities: ["Bergen"] },
    { name: "Trøndelag",             code: "50", cities: ["Trondheim"] },
    { name: "Rogaland",              code: "11", cities: ["Stavanger", "Sandnes"] },
    { name: "Viken",                 code: "30", cities: ["Drammen", "Fredrikstad", "Sarpsborg"] },
    { name: "Agder",                 code: "42", cities: ["Kristiansand"] },
    { name: "Troms og Finnmark",     code: "54", cities: ["Tromsø"] },
  ] },
  { name: "Pakistan", code: "PK", currency: { code: "PKR", symbol: "₨", name: "Pakistani Rupee" }, cities: ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Gujranwala", "Peshawar", "Multan", "Quetta", "Islamabad", "Bahawalpur"], states: [
    { name: "Sindh",                       code: "SD",  cities: ["Karachi"] },
    { name: "Punjab",                      code: "PB",  cities: ["Lahore", "Faisalabad", "Rawalpindi", "Gujranwala", "Multan", "Bahawalpur"] },
    { name: "Khyber Pakhtunkhwa",          code: "KP",  cities: ["Peshawar"] },
    { name: "Balochistan",                 code: "BA",  cities: ["Quetta"] },
    { name: "Islamabad Capital Territory", code: "ICT", cities: ["Islamabad"] },
  ] },
  { name: "Peru", code: "PE", currency: { code: "PEN", symbol: "S/.", name: "Peruvian Sol" }, cities: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Iquitos", "Cusco", "Chimbote", "Huancayo", "Tacna"], states: [
    { name: "Lima",        code: "LIM", cities: ["Lima"] },
    { name: "Arequipa",    code: "ARE", cities: ["Arequipa"] },
    { name: "La Libertad", code: "LAL", cities: ["Trujillo"] },
    { name: "Lambayeque",  code: "LAM", cities: ["Chiclayo"] },
    { name: "Piura",       code: "PIU", cities: ["Piura"] },
    { name: "Loreto",      code: "LOR", cities: ["Iquitos"] },
    { name: "Cusco",       code: "CUS", cities: ["Cusco"] },
    { name: "Áncash",      code: "ANC", cities: ["Chimbote"] },
    { name: "Junín",       code: "JUN", cities: ["Huancayo"] },
    { name: "Tacna",       code: "TAC", cities: ["Tacna"] },
  ] },
  { name: "Philippines", code: "PH", currency: { code: "PHP", symbol: "₱", name: "Philippine Peso" }, cities: ["Manila", "Quezon City", "Cebu City", "Davao City", "Caloocan", "Zamboanga City", "Taguig", "Antipolo", "Pasig", "Cagayan de Oro"], states: [
    { name: "Metro Manila",         code: "00", cities: ["Manila", "Quezon City", "Caloocan", "Taguig", "Pasig"] },
    { name: "Central Visayas",      code: "07", cities: ["Cebu City"] },
    { name: "Davao Region",         code: "11", cities: ["Davao City"] },
    { name: "Zamboanga Peninsula",  code: "09", cities: ["Zamboanga City"] },
    { name: "CALABARZON",           code: "40", cities: ["Antipolo"] },
    { name: "Northern Mindanao",    code: "10", cities: ["Cagayan de Oro"] },
  ] },
  { name: "Poland", code: "PL", currency: { code: "PLN", symbol: "zł", name: "Polish Złoty" }, cities: ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Katowice"], states: [
    { name: "Masovian",            code: "MZ", cities: ["Warsaw"] },
    { name: "Lesser Poland",       code: "MA", cities: ["Kraków"] },
    { name: "Łódź",                code: "LD", cities: ["Łódź"] },
    { name: "Lower Silesian",      code: "DS", cities: ["Wrocław"] },
    { name: "Greater Poland",      code: "WP", cities: ["Poznań"] },
    { name: "Pomeranian",          code: "PM", cities: ["Gdańsk"] },
    { name: "West Pomeranian",     code: "ZP", cities: ["Szczecin"] },
    { name: "Kuyavian-Pomeranian", code: "KP", cities: ["Bydgoszcz"] },
    { name: "Lublin",              code: "LU", cities: ["Lublin"] },
    { name: "Silesian",            code: "SL", cities: ["Katowice"] },
  ] },
  { name: "Portugal", code: "PT", currency: { code: "EUR", symbol: "€", name: "Euro" }, cities: ["Lisbon", "Porto", "Braga", "Amadora", "Funchal", "Coimbra", "Setúbal", "Almada", "Agualva-Cacém", "Aveiro"], states: [
    { name: "Lisbon",   code: "11", cities: ["Lisbon", "Amadora", "Almada", "Agualva-Cacém"] },
    { name: "Porto",    code: "13", cities: ["Porto"] },
    { name: "Braga",    code: "03", cities: ["Braga"] },
    { name: "Madeira",  code: "30", cities: ["Funchal"] },
    { name: "Coimbra",  code: "06", cities: ["Coimbra"] },
    { name: "Setúbal",  code: "15", cities: ["Setúbal"] },
    { name: "Aveiro",   code: "01", cities: ["Aveiro"] },
  ] },
  { name: "Romania", code: "RO", currency: { code: "RON", symbol: "lei", name: "Romanian Leu" }, cities: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova", "Brașov", "Galați", "Ploiești", "Oradea"], states: [
    { name: "Bucharest", code: "B",  cities: ["Bucharest"] },
    { name: "Cluj",      code: "CJ", cities: ["Cluj-Napoca"] },
    { name: "Timiș",     code: "TM", cities: ["Timișoara"] },
    { name: "Iași",      code: "IS", cities: ["Iași"] },
    { name: "Constanța", code: "CT", cities: ["Constanța"] },
    { name: "Dolj",      code: "DJ", cities: ["Craiova"] },
    { name: "Brașov",    code: "BV", cities: ["Brașov"] },
    { name: "Galați",    code: "GL", cities: ["Galați"] },
    { name: "Prahova",   code: "PH", cities: ["Ploiești"] },
    { name: "Bihor",     code: "BH", cities: ["Oradea"] },
  ] },
  { name: "Russia", code: "RU", currency: { code: "RUB", symbol: "₽", name: "Russian Ruble" }, cities: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Samara", "Omsk", "Rostov-on-Don", "Ufa", "Krasnoyarsk", "Voronezh", "Perm", "Volgograd"], states: [
    { name: "Moscow",                 code: "MOW", cities: ["Moscow"] },
    { name: "Saint Petersburg",       code: "SPE", cities: ["Saint Petersburg"] },
    { name: "Novosibirsk Oblast",     code: "NVS", cities: ["Novosibirsk"] },
    { name: "Sverdlovsk Oblast",      code: "SVE", cities: ["Yekaterinburg"] },
    { name: "Tatarstan",              code: "TA",  cities: ["Kazan"] },
    { name: "Nizhny Novgorod Oblast", code: "NIZ", cities: ["Nizhny Novgorod"] },
    { name: "Chelyabinsk Oblast",     code: "CHE", cities: ["Chelyabinsk"] },
    { name: "Samara Oblast",          code: "SAM", cities: ["Samara"] },
    { name: "Omsk Oblast",            code: "OMS", cities: ["Omsk"] },
    { name: "Rostov Oblast",          code: "ROS", cities: ["Rostov-on-Don"] },
    { name: "Bashkortostan",          code: "BA",  cities: ["Ufa"] },
    { name: "Krasnoyarsk Krai",       code: "KYA", cities: ["Krasnoyarsk"] },
    { name: "Voronezh Oblast",        code: "VOR", cities: ["Voronezh"] },
    { name: "Perm Krai",              code: "PER", cities: ["Perm"] },
    { name: "Volgograd Oblast",       code: "VGG", cities: ["Volgograd"] },
  ] },
  { name: "Saudi Arabia", code: "SA", currency: { code: "SAR", symbol: "﷼", name: "Saudi Riyal" }, cities: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Tabuk", "Qatif", "Buraidah", "Hail"], states: [
    { name: "Riyadh",        code: "01", cities: ["Riyadh"] },
    { name: "Makkah",        code: "02", cities: ["Jeddah", "Mecca"] },
    { name: "Medina",        code: "03", cities: ["Medina"] },
    { name: "Eastern",       code: "04", cities: ["Dammam", "Khobar", "Qatif"] },
    { name: "Tabuk",         code: "07", cities: ["Tabuk"] },
    { name: "Al-Qassim",     code: "05", cities: ["Buraidah"] },
    { name: "Ha'il",         code: "06", cities: ["Hail"] },
  ] },
  { name: "Singapore", code: "SG", currency: { code: "SGD", symbol: "S$", name: "Singapore Dollar" }, cities: ["Singapore", "Jurong East", "Woodlands", "Tampines", "Clementi", "Queenstown", "Bedok", "Ang Mo Kio", "Bishan", "Toa Payoh"] },
  { name: "South Africa", code: "ZA", currency: { code: "ZAR", symbol: "R", name: "South African Rand" }, cities: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "East London", "Nelspruit", "Polokwane", "Kimberley"], states: [
    { name: "Gauteng",         code: "GP", cities: ["Johannesburg", "Pretoria"] },
    { name: "Western Cape",    code: "WC", cities: ["Cape Town"] },
    { name: "KwaZulu-Natal",   code: "KZN", cities: ["Durban"] },
    { name: "Eastern Cape",    code: "EC", cities: ["Port Elizabeth", "East London"] },
    { name: "Free State",      code: "FS", cities: ["Bloemfontein"] },
    { name: "Mpumalanga",      code: "MP", cities: ["Nelspruit"] },
    { name: "Limpopo",         code: "LP", cities: ["Polokwane"] },
    { name: "Northern Cape",   code: "NC", cities: ["Kimberley"] },
  ] },
  { name: "South Korea", code: "KR", currency: { code: "KRW", symbol: "₩", name: "South Korean Won" }, cities: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Goyang"], states: [
    { name: "Seoul",            code: "11", cities: ["Seoul"] },
    { name: "Busan",            code: "26", cities: ["Busan"] },
    { name: "Incheon",          code: "28", cities: ["Incheon"] },
    { name: "Daegu",            code: "27", cities: ["Daegu"] },
    { name: "Daejeon",          code: "30", cities: ["Daejeon"] },
    { name: "Gwangju",          code: "29", cities: ["Gwangju"] },
    { name: "Gyeonggi",         code: "41", cities: ["Suwon", "Goyang"] },
    { name: "Ulsan",            code: "31", cities: ["Ulsan"] },
    { name: "South Gyeongsang", code: "48", cities: ["Changwon"] },
  ] },
  { name: "Spain", code: "ES", currency: { code: "EUR", symbol: "€", name: "Euro" }, cities: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga", "Murcia", "Palma", "Las Palmas", "Bilbao", "Alicante", "Córdoba", "Valladolid", "Vigo", "Gijón"], states: [
    { name: "Madrid",              code: "MD", cities: ["Madrid"] },
    { name: "Catalonia",           code: "CT", cities: ["Barcelona"] },
    { name: "Valencian Community", code: "VC", cities: ["Valencia", "Alicante"] },
    { name: "Andalusia",           code: "AN", cities: ["Seville", "Málaga", "Córdoba"] },
    { name: "Aragon",              code: "AR", cities: ["Zaragoza"] },
    { name: "Region of Murcia",    code: "MC", cities: ["Murcia"] },
    { name: "Balearic Islands",    code: "IB", cities: ["Palma"] },
    { name: "Canary Islands",      code: "CN", cities: ["Las Palmas"] },
    { name: "Basque Country",      code: "PV", cities: ["Bilbao"] },
    { name: "Castile and León",    code: "CL", cities: ["Valladolid"] },
    { name: "Galicia",             code: "GA", cities: ["Vigo"] },
    { name: "Asturias",            code: "AS", cities: ["Gijón"] },
  ] },
  { name: "Sweden", code: "SE", currency: { code: "SEK", symbol: "kr", name: "Swedish Krona" }, cities: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås", "Örebro", "Linköping", "Helsingborg", "Jönköping", "Norrköping"], states: [
    { name: "Stockholm",     code: "AB", cities: ["Stockholm"] },
    { name: "Västra Götaland", code: "O", cities: ["Gothenburg"] },
    { name: "Skåne",         code: "M",  cities: ["Malmö", "Helsingborg"] },
    { name: "Uppsala",       code: "C",  cities: ["Uppsala"] },
    { name: "Västmanland",   code: "U",  cities: ["Västerås"] },
    { name: "Örebro",        code: "T",  cities: ["Örebro"] },
    { name: "Östergötland",  code: "E",  cities: ["Linköping", "Norrköping"] },
    { name: "Jönköping",     code: "F",  cities: ["Jönköping"] },
  ] },
  { name: "Switzerland", code: "CH", currency: { code: "CHF", symbol: "Fr", name: "Swiss Franc" }, cities: ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Winterthur", "Lucerne", "St. Gallen", "Lugano", "Biel"], states: [
    { name: "Zurich",        code: "ZH", cities: ["Zurich", "Winterthur"] },
    { name: "Geneva",        code: "GE", cities: ["Geneva"] },
    { name: "Basel-City",    code: "BS", cities: ["Basel"] },
    { name: "Bern",          code: "BE", cities: ["Bern", "Biel"] },
    { name: "Vaud",          code: "VD", cities: ["Lausanne"] },
    { name: "Lucerne",       code: "LU", cities: ["Lucerne"] },
    { name: "St. Gallen",    code: "SG", cities: ["St. Gallen"] },
    { name: "Ticino",        code: "TI", cities: ["Lugano"] },
  ] },
  { name: "Taiwan", code: "TW", currency: { code: "TWD", symbol: "NT$", name: "New Taiwan Dollar" }, cities: ["Taipei", "New Taipei", "Kaohsiung", "Taichung", "Tainan", "Hsinchu", "Keelung", "Taoyuan", "Chiayi", "Changhua"], states: [
    { name: "Taipei",         code: "TPE", cities: ["Taipei"] },
    { name: "New Taipei",     code: "NWT", cities: ["New Taipei"] },
    { name: "Kaohsiung",      code: "KHH", cities: ["Kaohsiung"] },
    { name: "Taichung",       code: "TXG", cities: ["Taichung"] },
    { name: "Tainan",         code: "TNN", cities: ["Tainan"] },
    { name: "Hsinchu City",   code: "HSZ", cities: ["Hsinchu"] },
    { name: "Keelung",        code: "KEE", cities: ["Keelung"] },
    { name: "Taoyuan",        code: "TAO", cities: ["Taoyuan"] },
    { name: "Chiayi City",    code: "CYI", cities: ["Chiayi"] },
    { name: "Changhua County", code: "CHA", cities: ["Changhua"] },
  ] },
  { name: "Thailand", code: "TH", currency: { code: "THB", symbol: "฿", name: "Thai Baht" }, cities: ["Bangkok", "Chiang Mai", "Pattaya", "Phuket", "Hat Yai", "Khon Kaen", "Nakhon Ratchasima", "Udon Thani", "Chon Buri", "Rayong"], states: [
    { name: "Bangkok",            code: "10", cities: ["Bangkok"] },
    { name: "Chiang Mai",         code: "50", cities: ["Chiang Mai"] },
    { name: "Chon Buri",          code: "20", cities: ["Pattaya", "Chon Buri"] },
    { name: "Phuket",             code: "83", cities: ["Phuket"] },
    { name: "Songkhla",           code: "90", cities: ["Hat Yai"] },
    { name: "Khon Kaen",          code: "40", cities: ["Khon Kaen"] },
    { name: "Nakhon Ratchasima",  code: "30", cities: ["Nakhon Ratchasima"] },
    { name: "Udon Thani",         code: "41", cities: ["Udon Thani"] },
    { name: "Rayong",             code: "21", cities: ["Rayong"] },
  ] },
  { name: "Turkey", code: "TR", currency: { code: "TRY", symbol: "₺", name: "Turkish Lira" }, cities: ["Istanbul", "Ankara", "Izmir", "Bursa", "Adana", "Gaziantep", "Konya", "Antalya", "Kayseri", "Mersin", "Diyarbakır", "Manisa", "Samsun", "Eskişehir", "Trabzon"], states: [
    { name: "Istanbul",   code: "34", cities: ["Istanbul"] },
    { name: "Ankara",     code: "06", cities: ["Ankara"] },
    { name: "İzmir",      code: "35", cities: ["Izmir"] },
    { name: "Bursa",      code: "16", cities: ["Bursa"] },
    { name: "Adana",      code: "01", cities: ["Adana"] },
    { name: "Gaziantep",  code: "27", cities: ["Gaziantep"] },
    { name: "Konya",      code: "42", cities: ["Konya"] },
    { name: "Antalya",    code: "07", cities: ["Antalya"] },
    { name: "Kayseri",    code: "38", cities: ["Kayseri"] },
    { name: "Mersin",     code: "33", cities: ["Mersin"] },
    { name: "Diyarbakır", code: "21", cities: ["Diyarbakır"] },
    { name: "Manisa",     code: "45", cities: ["Manisa"] },
    { name: "Samsun",     code: "55", cities: ["Samsun"] },
    { name: "Eskişehir",  code: "26", cities: ["Eskişehir"] },
    { name: "Trabzon",    code: "61", cities: ["Trabzon"] },
  ] },
  { name: "Ukraine", code: "UA", currency: { code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia" }, cities: ["Kyiv", "Kharkiv", "Odessa", "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv", "Kryvyi Rih", "Mykolaiv", "Mariupol"], states: [
    { name: "Kyiv",                  code: "30", cities: ["Kyiv"] },
    { name: "Kharkiv Oblast",        code: "63", cities: ["Kharkiv"] },
    { name: "Odessa Oblast",         code: "51", cities: ["Odessa"] },
    { name: "Dnipropetrovsk Oblast", code: "12", cities: ["Dnipro", "Kryvyi Rih"] },
    { name: "Donetsk Oblast",        code: "14", cities: ["Donetsk", "Mariupol"] },
    { name: "Zaporizhzhia Oblast",   code: "23", cities: ["Zaporizhzhia"] },
    { name: "Lviv Oblast",           code: "46", cities: ["Lviv"] },
    { name: "Mykolaiv Oblast",       code: "48", cities: ["Mykolaiv"] },
  ] },
  { name: "United Arab Emirates", code: "AE", currency: { code: "AED", symbol: "د.إ", name: "UAE Dirham" }, cities: ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain", "Khor Fakkan", "Dibba Al-Hisn"], states: [
    { name: "Dubai",            code: "DU", cities: ["Dubai"] },
    { name: "Abu Dhabi",        code: "AZ", cities: ["Abu Dhabi", "Al Ain"] },
    { name: "Sharjah",          code: "SH", cities: ["Sharjah", "Khor Fakkan"] },
    { name: "Ajman",            code: "AJ", cities: ["Ajman"] },
    { name: "Ras Al Khaimah",   code: "RK", cities: ["Ras Al Khaimah"] },
    { name: "Fujairah",         code: "FU", cities: ["Fujairah", "Dibba Al-Hisn"] },
    { name: "Umm Al Quwain",    code: "UQ", cities: ["Umm Al Quwain"] },
  ] },
  { name: "United Kingdom", code: "GB", currency: { code: "GBP", symbol: "£", name: "British Pound" }, cities: ["London", "Birmingham", "Manchester", "Leeds", "Glasgow", "Liverpool", "Bristol", "Edinburgh", "Sheffield", "Cardiff", "Belfast", "Leicester", "Nottingham", "Newcastle", "Plymouth", "Southampton", "Reading", "Derby", "Coventry", "Brighton"], states: [
    { name: "England",          code: "ENG", cities: ["London", "Birmingham", "Manchester", "Leeds", "Liverpool", "Bristol", "Sheffield", "Leicester", "Nottingham", "Newcastle", "Plymouth", "Southampton", "Reading", "Derby", "Coventry", "Brighton"] },
    { name: "Scotland",         code: "SCT", cities: ["Glasgow", "Edinburgh"] },
    { name: "Wales",            code: "WLS", cities: ["Cardiff"] },
    { name: "Northern Ireland", code: "NIR", cities: ["Belfast"] },
  ] },
  { name: "United States", code: "US", currency: { code: "USD", symbol: "$", name: "US Dollar" }, cities: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "San Francisco", "Indianapolis", "Seattle", "Denver", "Nashville", "Oklahoma City", "El Paso", "Washington DC", "Boston", "Las Vegas", "Portland", "Memphis", "Louisville", "Baltimore", "Atlanta", "Miami", "Minneapolis", "Raleigh", "Tucson", "Orlando", "Pittsburgh", "Sacramento"], states: [
    { name: "New York",       code: "NY", cities: [
      "New York", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany",
      "New Rochelle", "Mount Vernon", "Schenectady", "Utica", "White Plains", "Hempstead",
      "Troy", "Niagara Falls", "Binghamton", "Freeport", "Valley Stream", "Long Beach",
      "Spring Valley", "Rome", "Ithaca", "Poughkeepsie", "North Tonawanda", "Jamestown",
      "Elmira", "Lindenhurst", "Auburn", "Watertown", "Glen Cove", "Saratoga Springs",
      "Middletown", "Kingston", "Peekskill", "Lockport", "Plattsburgh", "Cortland",
      "Oswego", "Newburgh", "Beacon", "Rye", "Mamaroneck", "Harrison",
      "Scarsdale", "Bronxville", "Larchmont", "Tarrytown", "Sleepy Hollow", "Ossining",
      "Garden City", "Great Neck", "Manhasset", "Port Washington", "Roslyn", "Mineola",
      "Massapequa", "Levittown", "Hicksville", "Huntington", "Smithtown", "Stony Brook",
      "Riverhead", "Southampton", "East Hampton", "Montauk", "Sag Harbor", "Bridgehampton",
      "Brooklyn", "Queens", "Bronx", "Staten Island", "Manhattan",
    ] },
    { name: "California",     code: "CA", cities: [
      "Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno", "Sacramento",
      "Long Beach", "Oakland", "Bakersfield", "Anaheim", "Santa Ana", "Riverside",
      "Stockton", "Irvine", "Chula Vista", "Fremont", "San Bernardino", "Modesto",
      "Fontana", "Oxnard", "Moreno Valley", "Huntington Beach", "Glendale", "Santa Clarita",
      "Garden Grove", "Oceanside", "Rancho Cucamonga", "Santa Rosa", "Ontario", "Elk Grove",
      "Corona", "Lancaster", "Palmdale", "Hayward", "Salinas", "Pomona", "Sunnyvale",
      "Escondido", "Torrance", "Pasadena", "Roseville", "Orange", "Fullerton",
      "Visalia", "Thousand Oaks", "Concord", "Simi Valley", "Santa Clara", "Victorville",
      "Berkeley", "El Monte", "Vallejo", "Downey", "Costa Mesa", "Carlsbad",
      "Inglewood", "Fairfield", "Ventura", "Temecula", "Antioch", "Richmond",
      "West Covina", "Murrieta", "Norwalk", "Daly City", "Burbank", "Santa Maria",
      "Clovis", "El Cajon", "San Mateo", "Rialto", "Vista", "Jurupa Valley",
      "Compton", "Mission Viejo", "Vacaville", "South Gate", "Carson", "Hesperia",
      "Santa Monica", "Westminster", "Redding", "Santa Barbara", "Chico", "Newport Beach",
      "San Leandro", "Whittier", "Hawthorne", "San Marcos", "Citrus Heights", "Tracy",
      "Alhambra", "Indio", "Livermore", "Buena Park", "Menifee", "Hemet",
      "Lakewood", "Merced", "Chino", "Redwood City", "Lake Forest", "Napa",
      "Tustin", "Bellflower", "Mountain View", "Chino Hills", "Baldwin Park", "Alameda",
      "Upland", "San Ramon", "Folsom", "Pleasanton", "Union City", "Perris",
      "Manteca", "Lynwood", "Apple Valley", "Redlands", "Turlock", "Milpitas",
      "Redondo Beach", "Rancho Cordova", "Yorba Linda", "Palo Alto", "Davis", "Camarillo",
      "Walnut Creek", "South San Francisco", "San Clemente", "Pittsburg", "Laguna Niguel", "Pico Rivera",
      "Montebello", "Lodi", "Madera", "Santa Cruz", "La Habra", "Encinitas",
      "Monterey Park", "Tulare", "Cupertino", "Gardena", "National City", "Rocklin",
      "Petaluma", "Huntington Park", "San Rafael", "La Mesa", "Arcadia", "Fountain Valley",
      "Diamond Bar", "Woodland", "Santee", "Lake Elsinore", "Porterville", "Paramount",
      "Hanford", "Rosemead", "Eastvale", "Yuba City", "Highland", "San Luis Obispo",
      "Novato", "Brentwood", "Colton", "Cathedral City", "Watsonville", "Placentia",
      "Glendora", "Gilroy", "Palm Desert", "Cerritos", "West Sacramento", "Aliso Viejo",
      "Poway", "La Mirada", "Rancho Santa Margarita", "Cypress", "Dublin", "Covina",
      "Azusa", "Palm Springs", "San Gabriel", "Beaumont", "Ceres", "San Jacinto",
      "Lincoln", "Newark", "Lompoc", "El Centro", "Danville", "Bell Gardens",
      "Coachella", "Rancho Palos Verdes", "San Bruno", "Rohnert Park", "Brea", "La Puente",
      "Yucaipa", "Campbell", "Morgan Hill", "Foster City", "Belmont",
      "Pacifica", "Cudahy", "Calabasas", "Burlingame", "Banning", "La Quinta",
      "Lawndale", "Half Moon Bay", "Los Altos", "Saratoga", "Menlo Park", "Atherton",
      "Hillsborough", "Larkspur", "Mill Valley", "Sausalito", "Tiburon", "Corte Madera",
    ] },
    { name: "Texas",          code: "TX", cities: [
      "Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington",
      "Corpus Christi", "Plano", "Laredo", "Lubbock", "Garland", "Irving", "Amarillo",
      "Grand Prairie", "Brownsville", "McKinney", "Frisco", "Pasadena", "Mesquite",
      "Killeen", "McAllen", "Carrollton", "Midland", "Waco", "Denton", "Abilene",
      "Beaumont", "Round Rock", "Odessa", "Wichita Falls", "Richardson", "Lewisville",
      "Tyler", "College Station", "Pearland", "San Angelo", "Allen", "League City",
      "Sugar Land", "Longview", "Edinburg", "Mission", "Bryan", "Baytown", "Pharr",
      "Temple", "Missouri City", "Flower Mound", "Harlingen", "North Richland Hills",
      "Victoria", "Conroe", "New Braunfels", "Mansfield", "Cedar Park", "Rowlett",
      "Port Arthur", "Euless", "Georgetown", "Pflugerville", "DeSoto", "San Marcos",
      "Grapevine", "Bedford", "Galveston", "Cedar Hill", "Texas City", "Wylie",
      "Haltom City", "Keller", "Coppell", "Rockwall", "Huntsville", "Duncanville",
      "Sherman", "The Colony", "Burleson", "Hurst", "Lancaster", "Texarkana",
      "Friendswood", "Weslaco", "Schertz", "Plainview", "Sugarland", "Round Rock",
    ] },
    { name: "Florida",        code: "FL", cities: [
      "Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Hialeah",
      "Tallahassee", "Port St. Lucie", "Cape Coral", "Fort Lauderdale", "Pembroke Pines",
      "Hollywood", "Miramar", "Gainesville", "Coral Springs", "Clearwater", "Miami Gardens",
      "Palm Bay", "West Palm Beach", "Pompano Beach", "Lakeland", "Davie", "Sunrise",
      "Boca Raton", "Deltona", "Plantation", "Fort Myers", "Largo", "Deerfield Beach",
      "Melbourne", "Boynton Beach", "Lauderhill", "Weston", "Kissimmee", "Homestead",
      "Delray Beach", "Tamarac", "Daytona Beach", "Wellington", "North Miami", "Jupiter",
      "North Port", "Coconut Creek", "Sanford", "Margate", "Doral", "Ocala",
      "Sarasota", "Bradenton", "Pensacola", "Bonita Springs", "Pinellas Park", "Coral Gables",
      "Naples", "Estero", "Apopka", "Royal Palm Beach", "Riviera Beach", "Lake Worth",
      "Hallandale Beach", "Aventura", "Greenacres", "Ormond Beach", "Oakland Park",
      "St. Augustine", "Plant City", "Cooper City", "Winter Park", "Casselberry",
      "Key West", "Winter Garden", "Titusville", "Vero Beach", "Stuart", "Port Orange",
      "Panama City", "Altamonte Springs", "North Lauderdale", "Sebastian", "Cutler Bay",
    ] },
    { name: "Illinois",       code: "IL", cities: [
      "Chicago", "Aurora", "Joliet", "Naperville", "Rockford", "Elgin", "Springfield",
      "Peoria", "Champaign", "Waukegan", "Cicero", "Bloomington", "Arlington Heights",
      "Evanston", "Decatur", "Schaumburg", "Bolingbrook", "Palatine", "Skokie",
      "Des Plaines", "Orland Park", "Tinley Park", "Oak Lawn", "Berwyn", "Mount Prospect",
      "Wheaton", "Hoffman Estates", "Oak Park", "Downers Grove", "Elmhurst", "Glenview",
      "Lombard", "Buffalo Grove", "Bartlett", "Crystal Lake", "Carol Stream", "Streamwood",
      "Quincy", "Urbana", "Plainfield", "Hanover Park", "Carpentersville", "Pekin",
      "Belleville", "Romeoville", "Park Ridge", "Calumet City", "Northbrook", "Wheeling",
      "Addison", "Elk Grove Village", "Highland Park", "Lansing", "Galesburg", "Danville",
      "Burbank", "DeKalb", "Saint Charles", "Lake in the Hills", "Woodridge", "North Chicago",
      "New Lenox", "Vernon Hills", "Granite City", "Mundelein", "Glendale Heights",
      "Alton", "Belvidere", "Freeport", "Loves Park", "Edwardsville", "Wood River",
    ] },
    { name: "Pennsylvania",   code: "PA", cities: [
      "Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Scranton",
      "Bethlehem", "Lancaster", "Harrisburg", "York", "Wilkes-Barre", "Altoona",
      "Chester", "Williamsport", "Easton", "Lebanon", "Hazleton", "New Castle",
      "Johnstown", "McKeesport", "Hermitage", "State College", "Norristown", "Pottstown",
      "King of Prussia", "Bensalem", "Levittown", "West Chester", "Doylestown", "Lansdale",
      "Phoenixville", "Pottsville", "Carlisle", "Sharon", "Greensburg", "Butler",
      "Coatesville", "Lock Haven", "Sunbury", "Meadville", "Indiana", "Beaver Falls",
      "DuBois", "Bradford", "Oil City", "Washington", "Aliquippa", "Uniontown",
      "Bristol", "Media", "Wayne", "Radnor", "Newtown", "Yardley", "New Hope",
      "Ardmore", "Bryn Mawr", "Conshohocken", "Plymouth Meeting", "Blue Bell",
    ] },
    { name: "Ohio",           code: "OH", cities: [
      "Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton",
      "Parma", "Canton", "Youngstown", "Lorain", "Hamilton", "Springfield",
      "Kettering", "Elyria", "Lakewood", "Cuyahoga Falls", "Middletown", "Euclid",
      "Newark", "Mansfield", "Mentor", "Beavercreek", "Cleveland Heights", "Strongsville",
      "Dublin", "Fairfield", "Findlay", "Warren", "Lancaster", "Lima",
      "Huber Heights", "Westerville", "Marion", "Grove City", "Reynoldsburg", "Delaware",
      "Brunswick", "Stow", "Upper Arlington", "Gahanna", "North Olmsted", "Westlake",
      "Massillon", "North Royalton", "Mason", "North Ridgeville", "Fairborn", "Wooster",
      "Medina", "Bowling Green", "Riverside", "Hilliard", "Garfield Heights", "Shaker Heights",
    ] },
    { name: "Georgia",        code: "GA", cities: [
      "Atlanta", "Augusta", "Columbus", "Macon", "Savannah", "Athens", "Sandy Springs",
      "South Fulton", "Roswell", "Johns Creek", "Albany", "Warner Robins", "Alpharetta",
      "Marietta", "Valdosta", "Smyrna", "Dunwoody", "Brookhaven", "Stonecrest",
      "Mableton", "Rome", "Peachtree Corners", "East Point", "Milton", "Gainesville",
      "Hinesville", "Peachtree City", "Newnan", "Dalton", "Douglasville", "Kennesaw",
      "LaGrange", "Statesboro", "Lawrenceville", "Tucker", "Duluth", "Stockbridge",
      "Carrollton", "Woodstock", "Canton", "Griffin", "Decatur", "Snellville",
      "Acworth", "Suwanee", "Cartersville", "Forest Park", "Pooler", "Union City",
      "Riverdale", "Hampton", "Mcdonough", "Fayetteville", "Conyers", "Lithonia",
    ] },
    { name: "North Carolina", code: "NC", cities: [
      "Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville",
      "Cary", "Wilmington", "High Point", "Concord", "Greenville", "Asheville",
      "Gastonia", "Jacksonville", "Chapel Hill", "Rocky Mount", "Burlington", "Huntersville",
      "Wilson", "Kannapolis", "Apex", "Hickory", "Wake Forest", "Indian Trail",
      "Mooresville", "Goldsboro", "Monroe", "Salisbury", "Holly Springs", "Matthews",
      "New Bern", "Sanford", "Cornelius", "Garner", "Thomasville", "Statesville",
      "Mint Hill", "Asheboro", "Kernersville", "Morrisville", "Lumberton", "Kinston",
      "Carrboro", "Havelock", "Shelby", "Clemmons", "Lexington", "Clayton",
      "Boone", "Elizabeth City", "Hope Mills", "Knightdale", "Eden", "Henderson",
    ] },
    { name: "Michigan",       code: "MI", cities: [
      "Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor", "Lansing",
      "Flint", "Dearborn", "Livonia", "Troy", "Westland", "Farmington Hills",
      "Kalamazoo", "Wyoming", "Southfield", "Rochester Hills", "Taylor", "Pontiac",
      "St. Clair Shores", "Royal Oak", "Novi", "Dearborn Heights", "Battle Creek", "Saginaw",
      "Kentwood", "East Lansing", "Roseville", "Portage", "Midland", "Lincoln Park",
      "Muskegon", "Bay City", "Holland", "Eastpointe", "Madison Heights", "Oak Park",
      "Burton", "Jackson", "Port Huron", "Auburn Hills", "Garden City", "Inkster",
      "Mount Pleasant", "Wyandotte", "Romulus", "Birmingham", "Berkley", "Ferndale",
      "Hamtramck", "Allen Park", "Marquette", "Traverse City", "Adrian", "Norton Shores",
    ] },
    { name: "Washington",     code: "WA", cities: [
      "Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kent", "Everett",
      "Renton", "Spokane Valley", "Federal Way", "Yakima", "Kirkland", "Bellingham",
      "Kennewick", "Auburn", "Pasco", "Marysville", "Lakewood", "Redmond", "Shoreline",
      "Richland", "Sammamish", "Burien", "Olympia", "Lacey", "Edmonds", "Bremerton",
      "Puyallup", "Bothell", "Lynnwood", "Issaquah", "Wenatchee", "Mount Vernon",
      "University Place", "Walla Walla", "Pullman", "Des Moines", "Maple Valley", "Mercer Island",
      "Bainbridge Island", "Oak Harbor", "Kenmore", "Moses Lake", "Camas", "Mukilteo",
      "Mountlake Terrace", "Tukwila", "SeaTac", "Covington", "Lake Stevens", "Bonney Lake",
      "Snohomish", "Monroe", "Port Angeles", "Centralia", "Anacortes", "Tumwater",
    ] },
    { name: "Arizona",        code: "AZ", cities: [
      "Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Gilbert", "Glendale",
      "Tempe", "Peoria", "Surprise", "Yuma", "San Tan Valley", "Avondale", "Goodyear",
      "Flagstaff", "Buckeye", "Lake Havasu City", "Casa Grande", "Sierra Vista", "Maricopa",
      "Oro Valley", "Prescott", "Bullhead City", "Prescott Valley", "Apache Junction", "Marana",
      "El Mirage", "Kingman", "Queen Creek", "Sahuarita", "Fountain Hills", "Nogales",
      "Douglas", "Eloy", "Payson", "Somerton", "Paradise Valley", "Coolidge", "Cottonwood",
      "Camp Verde", "Chino Valley", "Show Low", "Sedona", "Winslow", "Globe", "Page",
    ] },
    { name: "Massachusetts",  code: "MA", cities: [
      "Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton",
      "New Bedford", "Quincy", "Lynn", "Fall River", "Newton", "Lawrence",
      "Somerville", "Framingham", "Haverhill", "Waltham", "Malden", "Brookline",
      "Plymouth", "Medford", "Taunton", "Chicopee", "Weymouth", "Revere",
      "Peabody", "Methuen", "Barnstable", "Pittsfield", "Attleboro", "Arlington",
      "Everett", "Salem", "Westfield", "Leominster", "Fitchburg", "Holyoke",
      "Beverly", "Marlborough", "Woburn", "Chelsea", "Braintree", "Natick",
      "Watertown", "Randolph", "Franklin", "North Andover", "Andover", "Lexington",
      "Burlington", "Wellesley", "Needham", "Belmont", "Reading", "Wakefield",
      "Concord", "Lincoln", "Sudbury", "Wayland", "Acton", "Bedford",
      "Hingham", "Cohasset", "Scituate", "Marshfield", "Duxbury", "Sandwich",
      "Cape Cod", "Provincetown", "Hyannis", "Falmouth", "Chatham", "Wellfleet",
      "Nantucket", "Edgartown", "Vineyard Haven", "Oak Bluffs", "Williamstown", "Amherst",
    ] },
    { name: "Virginia",       code: "VA", cities: [
      "Virginia Beach", "Norfolk", "Chesapeake", "Arlington", "Richmond", "Newport News",
      "Alexandria", "Hampton", "Roanoke", "Portsmouth", "Suffolk", "Lynchburg",
      "Harrisonburg", "Leesburg", "Charlottesville", "Danville", "Manassas", "Blacksburg",
      "Petersburg", "Fredericksburg", "Winchester", "Salem", "Staunton", "Fairfax",
      "Hopewell", "Waynesboro", "Herndon", "Reston", "Tysons", "McLean",
      "Vienna", "Centreville", "Burke", "Springfield", "Annandale", "Ashburn",
      "Sterling", "Chantilly", "South Riding", "Stafford", "Woodbridge", "Dale City",
      "Lake Ridge", "Manassas Park", "Falls Church", "Williamsburg", "Bristol", "Front Royal",
    ] },
    { name: "Maryland",       code: "MD", cities: [
      "Baltimore", "Frederick", "Rockville", "Gaithersburg", "Bowie", "Hagerstown",
      "Annapolis", "Salisbury", "College Park", "Greenbelt", "Cumberland", "Westminster",
      "Hyattsville", "Takoma Park", "Easton", "Laurel", "Aberdeen", "Cambridge",
      "Bethesda", "Silver Spring", "Wheaton", "Germantown", "Columbia", "Ellicott City",
      "Towson", "Pikesville", "Glen Burnie", "Severna Park", "Bel Air", "Catonsville",
      "Dundalk", "Essex", "Parkville", "Owings Mills", "Reisterstown", "Olney",
      "Potomac", "North Bethesda", "Chevy Chase", "Kensington", "Beltsville", "Adelphi",
    ] },
    { name: "Colorado",       code: "CO", cities: [
      "Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Thornton",
      "Arvada", "Westminster", "Pueblo", "Centennial", "Boulder", "Greeley",
      "Longmont", "Loveland", "Broomfield", "Grand Junction", "Castle Rock", "Commerce City",
      "Parker", "Littleton", "Northglenn", "Brighton", "Englewood", "Wheat Ridge",
      "Lafayette", "Windsor", "Erie", "Evans", "Golden", "Louisville",
      "Montrose", "Durango", "Cañon City", "Greenwood Village", "Sterling", "Lone Tree",
      "Fountain", "Federal Heights", "Cherry Hills Village", "Glenwood Springs", "Aspen", "Vail",
      "Breckenridge", "Steamboat Springs", "Telluride", "Estes Park", "Frisco", "Silverthorne",
    ] },
    { name: "Minnesota",      code: "MN", cities: [
      "Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington", "Brooklyn Park",
      "Plymouth", "Maple Grove", "Woodbury", "St. Cloud", "Eagan", "Eden Prairie",
      "Coon Rapids", "Burnsville", "Blaine", "Lakeville", "Minnetonka", "Apple Valley",
      "Edina", "St. Louis Park", "Mankato", "Maplewood", "Moorhead", "Shakopee",
      "Cottage Grove", "Inver Grove Heights", "Richfield", "Roseville", "Andover", "Brooklyn Center",
      "Savage", "Fridley", "Chanhassen", "Chaska", "Champlin", "Ramsey",
      "White Bear Lake", "Prior Lake", "Rosemount", "Hastings", "Crystal", "New Brighton",
      "Golden Valley", "Stillwater", "Owatonna", "Bemidji", "Hopkins", "Anoka",
      "Northfield", "Faribault", "Hibbing", "Winona", "Willmar", "New Ulm",
    ] },
    { name: "Wisconsin",      code: "WI", cities: [
      "Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton",
      "Waukesha", "Eau Claire", "Oshkosh", "Janesville", "West Allis", "La Crosse",
      "Sheboygan", "Wauwatosa", "Fond du Lac", "Brookfield", "New Berlin", "Wausau",
      "Beloit", "Greenfield", "Franklin", "Menomonee Falls", "Oak Creek", "Manitowoc",
      "West Bend", "Sun Prairie", "Superior", "Stevens Point", "Neenah", "Fitchburg",
      "Muskego", "Watertown", "De Pere", "Marshfield", "Mount Pleasant", "Wisconsin Rapids",
      "Pleasant Prairie", "Caledonia", "Cudahy", "Menasha", "South Milwaukee", "Ashwaubenon",
      "Howard", "Onalaska", "Hudson", "Middleton", "Whitewater", "Mequon",
    ] },
    { name: "Tennessee",      code: "TN", cities: [
      "Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro",
      "Franklin", "Jackson", "Johnson City", "Bartlett", "Hendersonville", "Kingsport",
      "Smyrna", "Cleveland", "Brentwood", "Collierville", "Germantown", "Spring Hill",
      "Columbia", "La Vergne", "Cookeville", "Mount Juliet", "Lebanon", "Morristown",
      "Oak Ridge", "Maryville", "Bristol", "Gallatin", "Goodlettsville", "Sevierville",
      "Pigeon Forge", "Gatlinburg", "Dyersburg", "Athens", "Greeneville", "Tullahoma",
      "Springfield", "Dickson", "McMinnville", "Crossville", "Paris", "Union City",
    ] },
    { name: "Indiana",        code: "IN", cities: [
      "Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel", "Fishers",
      "Bloomington", "Hammond", "Gary", "Lafayette", "Muncie", "Noblesville",
      "Greenwood", "Anderson", "Elkhart", "Mishawaka", "Lawrence", "Jeffersonville",
      "Columbus", "Portage", "New Albany", "Richmond", "Westfield", "Goshen",
      "Valparaiso", "Michigan City", "Kokomo", "Plainfield", "Crown Point", "Schererville",
      "Highland", "Merrillville", "Munster", "Avon", "Marion", "West Lafayette",
      "Logansport", "Vincennes", "Crawfordsville", "Shelbyville", "Frankfort", "New Castle",
      "Terre Haute", "Madison", "Seymour", "Connersville", "Huntington", "Bedford",
    ] },
    { name: "Missouri",       code: "MO", cities: [
      "Kansas City", "St. Louis", "Springfield", "Columbia", "Independence", "Lee's Summit",
      "O'Fallon", "St. Joseph", "St. Charles", "St. Peters", "Blue Springs", "Florissant",
      "Joplin", "Chesterfield", "Jefferson City", "Cape Girardeau", "Oakville", "Wildwood",
      "Wentzville", "University City", "Ballwin", "Raytown", "Liberty", "Kirkwood",
      "Maryland Heights", "Hazelwood", "Gladstone", "Grandview", "Belton", "Webster Groves",
      "Mehlville", "Sedalia", "Nixa", "Ozark", "Raymore", "Warrensburg",
      "Rolla", "Farmington", "Poplar Bluff", "Hannibal", "Sikeston", "Marshall",
    ] },
    { name: "South Carolina", code: "SC", cities: [
      "Charleston", "Columbia", "North Charleston", "Mount Pleasant", "Rock Hill", "Greenville",
      "Summerville", "Sumter", "Goose Creek", "Hilton Head Island", "Florence", "Spartanburg",
      "Myrtle Beach", "Aiken", "Anderson", "Greer", "Mauldin", "Hanahan",
      "Greenwood", "North Augusta", "Easley", "Simpsonville", "Lexington", "Conway",
      "West Columbia", "North Myrtle Beach", "Clemson", "Orangeburg", "Cayce", "Bluffton",
      "Beaufort", "Gaffney", "Camden", "Fort Mill", "Tega Cay", "Irmo",
    ] },
    { name: "Alabama",        code: "AL", cities: [
      "Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa", "Hoover",
      "Dothan", "Auburn", "Decatur", "Madison", "Florence", "Gadsden",
      "Vestavia Hills", "Prattville", "Phenix City", "Alabaster", "Bessemer", "Enterprise",
      "Opelika", "Homewood", "Northport", "Anniston", "Prichard", "Athens",
      "Daphne", "Pelham", "Oxford", "Albertville", "Selma", "Mountain Brook",
      "Trussville", "Helena", "Talladega", "Fairhope", "Cullman", "Scottsboro",
    ] },
    { name: "Louisiana",      code: "LA", cities: [
      "New Orleans", "Baton Rouge", "Shreveport", "Metairie", "Lafayette", "Lake Charles",
      "Kenner", "Bossier City", "Monroe", "Alexandria", "Houma", "Marrero",
      "New Iberia", "Slidell", "Prairieville", "Central", "Terrytown", "Ruston",
      "Sulphur", "Hammond", "Natchitoches", "Gretna", "Chalmette", "Opelousas",
      "Pineville", "Zachary", "Bayou Cane", "Estelle", "DeRidder", "Crowley",
    ] },
    { name: "Kentucky",       code: "KY", cities: [
      "Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington", "Hopkinsville",
      "Richmond", "Florence", "Georgetown", "Henderson", "Elizabethtown", "Nicholasville",
      "Jeffersontown", "Frankfort", "Independence", "Paducah", "Radcliff", "Ashland",
      "Madisonville", "Winchester", "Erlanger", "Murray", "St. Matthews", "Danville",
      "Fort Thomas", "Newport", "Shively", "Shelbyville", "Berea", "Glasgow",
      "Bardstown", "Shepherdsville", "Somerset", "Lyndon", "Mount Washington", "Campbellsville",
    ] },
    { name: "Oregon",         code: "OR", cities: [
      "Portland", "Salem", "Eugene", "Gresham", "Hillsboro", "Beaverton",
      "Bend", "Medford", "Springfield", "Corvallis", "Albany", "Tigard",
      "Lake Oswego", "Keizer", "Grants Pass", "Oregon City", "McMinnville", "Redmond",
      "Tualatin", "West Linn", "Woodburn", "Forest Grove", "Newberg", "Wilsonville",
      "Roseburg", "Klamath Falls", "Ashland", "Milwaukie", "Sherwood", "Happy Valley",
      "Central Point", "Hermiston", "Coos Bay", "The Dalles", "Pendleton", "Troutdale",
      "Lebanon", "St. Helens", "Cornelius", "Damascus", "Gladstone", "La Grande",
    ] },
    { name: "Oklahoma",       code: "OK", cities: [
      "Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond", "Lawton",
      "Moore", "Midwest City", "Enid", "Stillwater", "Muskogee", "Bartlesville",
      "Owasso", "Shawnee", "Yukon", "Ardmore", "Ponca City", "Bixby",
      "Duncan", "Del City", "Jenks", "Sapulpa", "Mustang", "Bethany",
      "Sand Springs", "Altus", "Claremore", "El Reno", "McAlester", "Durant",
      "Tahlequah", "Chickasha", "Miami", "Ada", "Choctaw", "Glenpool",
    ] },
    { name: "Connecticut",    code: "CT", cities: [
      "Bridgeport", "New Haven", "Stamford", "Hartford", "Waterbury", "Norwalk",
      "Danbury", "New Britain", "West Hartford", "Greenwich", "Fairfield", "Hamden",
      "Bristol", "Meriden", "Manchester", "West Haven", "Milford", "Stratford",
      "East Hartford", "Middletown", "Wallingford", "Southington", "Shelton", "Norwich",
      "Trumbull", "Glastonbury", "Naugatuck", "Newington", "Cheshire", "Vernon",
      "Windsor", "New London", "Branford", "New Milford", "Westport", "Wethersfield",
      "Farmington", "Mansfield", "Ridgefield", "Berlin", "Avon", "Simsbury",
      "Watertown", "Guilford", "Bloomfield", "Plainville", "Darien", "New Canaan",
    ] },
    { name: "New Jersey",     code: "NJ", cities: [
      "Newark", "Jersey City", "Paterson", "Elizabeth", "Edison", "Lakewood",
      "Woodbridge", "Toms River", "Hamilton", "Trenton", "Clifton", "Camden",
      "Cherry Hill", "Brick", "Passaic", "Middletown", "Union City", "Old Bridge",
      "Gloucester Township", "East Orange", "Bayonne", "Franklin", "North Bergen", "Vineland",
      "Union", "Piscataway", "New Brunswick", "Jackson", "Wayne", "Irvington",
      "Parsippany", "Howell", "Perth Amboy", "Hoboken", "Plainfield", "West New York",
      "Bloomfield", "East Brunswick", "West Orange", "Sayreville", "Hackensack", "Linden",
      "Atlantic City", "Princeton", "Fort Lee", "Ewing", "Long Branch", "Fair Lawn",
      "Garfield", "Westfield", "Montclair", "Englewood", "Belleville", "Pennsauken",
      "Kearny", "Voorhees", "Mount Laurel", "Marlboro", "Manalapan", "Freehold",
      "Asbury Park", "Red Bank", "Morristown", "Summit", "Cranford", "Maplewood",
    ] },
    { name: "Nevada",         code: "NV", cities: [
      "Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks", "Carson City",
      "Fernley", "Elko", "Mesquite", "Boulder City", "Fallon", "Winnemucca",
      "West Wendover", "Ely", "Yerington", "Caliente", "Lovelock", "Spring Valley",
      "Paradise", "Summerlin", "Sunrise Manor", "Whitney", "Pahrump", "Incline Village",
    ] },
    { name: "Utah",           code: "UT", cities: [
      "Salt Lake City", "West Valley City", "West Jordan", "Provo", "Orem", "Sandy",
      "St. George", "Ogden", "Layton", "South Jordan", "Lehi", "Millcreek",
      "Taylorsville", "Logan", "Murray", "Draper", "Bountiful", "Riverton",
      "Herriman", "Spanish Fork", "Roy", "Pleasant Grove", "Cedar City", "Tooele",
      "Springville", "Cottonwood Heights", "Kaysville", "Holladay", "American Fork", "Clearfield",
      "Syracuse", "Saratoga Springs", "Eagle Mountain", "Washington", "Midvale", "Farmington",
      "Park City", "Heber City", "Vernal", "Brigham City", "North Ogden", "South Ogden",
    ] },
    { name: "Iowa",           code: "IA", cities: [
      "Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City", "Waterloo",
      "Ames", "West Des Moines", "Council Bluffs", "Ankeny", "Urbandale", "Cedar Falls",
      "Marion", "Bettendorf", "Marshalltown", "Mason City", "Clinton", "Burlington",
      "Ottumwa", "Fort Dodge", "Muscatine", "Coralville", "Johnston", "North Liberty",
      "Altoona", "Newton", "Indianola", "Dubuque", "Storm Lake", "Spencer",
    ] },
    { name: "Arkansas",       code: "AR", cities: [
      "Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro", "North Little Rock",
      "Conway", "Rogers", "Pine Bluff", "Bentonville", "Hot Springs", "Benton",
      "Texarkana", "Sherwood", "Jacksonville", "Russellville", "Bella Vista", "West Memphis",
      "Paragould", "Cabot", "Searcy", "Van Buren", "El Dorado", "Maumelle",
      "Bryant", "Siloam Springs", "Marion", "Harrison", "Hot Springs Village", "Mountain Home",
    ] },
    { name: "Mississippi",    code: "MS", cities: [
      "Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi", "Meridian",
      "Tupelo", "Olive Branch", "Greenville", "Horn Lake", "Pearl", "Madison",
      "Starkville", "Clinton", "Ridgeland", "Columbus", "Vicksburg", "Pascagoula",
      "Brandon", "Oxford", "Gautier", "Laurel", "Hernando", "Long Beach",
      "Natchez", "Cleveland", "Corinth", "Ocean Springs", "Greenwood", "Brookhaven",
    ] },
    { name: "Kansas",         code: "KS", cities: [
      "Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka", "Lawrence",
      "Shawnee", "Manhattan", "Lenexa", "Salina", "Hutchinson", "Leavenworth",
      "Leawood", "Dodge City", "Garden City", "Junction City", "Emporia", "Derby",
      "Prairie Village", "Liberal", "Hays", "Pittsburg", "Newton", "Gardner",
      "Great Bend", "McPherson", "El Dorado", "Ottawa", "Winfield", "Arkansas City",
    ] },
    { name: "Nebraska",       code: "NE", cities: [
      "Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney", "Fremont",
      "Hastings", "Norfolk", "North Platte", "Columbus", "Papillion", "La Vista",
      "Scottsbluff", "South Sioux City", "Beatrice", "Lexington", "Gering", "Alliance",
      "York", "Blair", "McCook", "Nebraska City", "Seward", "Crete",
    ] },
    { name: "Idaho",          code: "ID", cities: [
      "Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello", "Caldwell",
      "Coeur d'Alene", "Twin Falls", "Lewiston", "Post Falls", "Rexburg", "Moscow",
      "Eagle", "Kuna", "Ammon", "Chubbuck", "Hayden", "Mountain Home",
      "Blackfoot", "Garden City", "Jerome", "Burley", "Sandpoint", "Star",
    ] },
    { name: "New Hampshire",  code: "NH", cities: [
      "Manchester", "Nashua", "Concord", "Derry", "Dover", "Rochester",
      "Salem", "Merrimack", "Hudson", "Londonderry", "Keene", "Bedford",
      "Portsmouth", "Goffstown", "Laconia", "Hampton", "Milford", "Durham",
      "Exeter", "Windham", "Hooksett", "Claremont", "Lebanon", "Pelham",
    ] },
    { name: "Maine",          code: "ME", cities: [
      "Portland", "Lewiston", "Bangor", "South Portland", "Auburn", "Biddeford",
      "Sanford", "Saco", "Westbrook", "Augusta", "Waterville", "Brunswick",
      "Scarborough", "Windham", "Gorham", "Falmouth", "Cape Elizabeth", "Yarmouth",
      "Kennebunk", "Old Orchard Beach", "Topsham", "Orono", "Bath", "Brewer",
      "Rockland", "Belfast", "Ellsworth", "Bar Harbor", "Camden", "Kittery",
    ] },
    { name: "Hawaii",         code: "HI", cities: [
      "Honolulu", "East Honolulu", "Pearl City", "Hilo", "Waipahu", "Kailua",
      "Kaneohe", "Mililani Town", "Kahului", "Ewa Gentry", "Mililani Mauka", "Kihei",
      "Makakilo", "Wahiawa", "Schofield Barracks", "Wailuku", "Kapolei", "Ewa Beach",
      "Royal Kunia", "Halawa", "Waimalu", "Waianae", "Nanakuli", "Kailua-Kona",
      "Lahaina", "Hanalei", "Princeville", "Lihue", "Kapaa", "Waimea",
    ] },
    { name: "Alaska",         code: "AK", cities: [
      "Anchorage", "Fairbanks", "Juneau", "Wasilla", "Sitka", "Ketchikan",
      "Kenai", "Kodiak", "Bethel", "Palmer", "Homer", "Soldotna",
      "Valdez", "Nome", "Barrow", "Seward", "Cordova", "Dillingham",
      "Petersburg", "Wrangell", "Haines", "Skagway", "Talkeetna", "Girdwood",
    ] },
    { name: "West Virginia",  code: "WV", cities: [
      "Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling", "Weirton",
      "Fairmont", "Beckley", "Martinsburg", "Clarksburg", "South Charleston", "St. Albans",
      "Vienna", "Bluefield", "Moundsville", "Bridgeport", "Oak Hill", "Dunbar",
      "Elkins", "Hurricane", "Princeton", "Buckhannon", "Keyser", "Nitro",
    ] },
    { name: "Rhode Island",   code: "RI", cities: [
      "Providence", "Warwick", "Cranston", "Pawtucket", "East Providence", "Woonsocket",
      "Coventry", "Cumberland", "North Providence", "South Kingstown", "West Warwick", "Johnston",
      "North Kingstown", "Newport", "Bristol", "Lincoln", "Smithfield", "Central Falls",
      "Portsmouth", "Westerly", "Barrington", "Middletown", "Burrillville", "Tiverton",
      "East Greenwich", "Narragansett", "North Smithfield", "Warren", "Jamestown", "Block Island",
    ] },
    { name: "Montana",        code: "MT", cities: [
      "Billings", "Missoula", "Great Falls", "Bozeman", "Butte", "Helena",
      "Kalispell", "Havre", "Anaconda", "Miles City", "Belgrade", "Livingston",
      "Laurel", "Whitefish", "Lewistown", "Sidney", "Glendive", "Columbia Falls",
      "Polson", "Hamilton", "Dillon", "Hardin", "Glasgow", "Shelby",
      "Red Lodge", "Big Sky", "West Yellowstone",
    ] },
    { name: "Delaware",       code: "DE", cities: [
      "Wilmington", "Dover", "Newark", "Middletown", "Smyrna", "Milford",
      "Seaford", "Georgetown", "Elsmere", "New Castle", "Millsboro", "Laurel",
      "Harrington", "Camden", "Clayton", "Lewes", "Milton", "Rehoboth Beach",
      "Bethany Beach", "Bridgeville", "Selbyville", "Ocean View", "Dewey Beach",
    ] },
    { name: "South Dakota",   code: "SD", cities: [
      "Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown", "Mitchell",
      "Yankton", "Pierre", "Huron", "Spearfish", "Vermillion", "Brandon",
      "Box Elder", "Sturgis", "Madison", "Belle Fourche", "Harrisburg", "Tea",
      "Hot Springs", "Mobridge", "Lead", "Deadwood", "Custer",
    ] },
    { name: "North Dakota",   code: "ND", cities: [
      "Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo", "Williston",
      "Dickinson", "Mandan", "Jamestown", "Wahpeton", "Devils Lake", "Watford City",
      "Valley City", "Grafton", "Beulah", "Rugby", "Stanley", "Horace",
      "Casselton", "New Town", "Hazen", "Bottineau", "Lincoln", "Lisbon",
    ] },
    { name: "Vermont",        code: "VT", cities: [
      "Burlington", "South Burlington", "Rutland", "Essex Junction", "Barre", "Montpelier",
      "Winooski", "St. Albans", "Newport", "Vergennes", "Middlebury", "Brattleboro",
      "Bennington", "Springfield", "Bellows Falls", "Saint Johnsbury", "Morristown", "Hartford",
      "Stowe", "Killington", "Manchester", "Woodstock", "Waterbury", "Shelburne",
    ] },
    { name: "Wyoming",        code: "WY", cities: [
      "Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs", "Sheridan",
      "Green River", "Evanston", "Riverton", "Jackson", "Cody", "Rawlins",
      "Lander", "Torrington", "Powell", "Douglas", "Worland", "Buffalo",
      "Wheatland", "Newcastle", "Mills", "Thermopolis", "Kemmerer", "Pinedale",
      "Star Valley Ranch", "Afton", "Saratoga", "Lyman", "Mountain View",
    ] },
    { name: "D.C.",           code: "DC", cities: ["Washington DC"] },
  ] },
  { name: "Uruguay", code: "UY", currency: { code: "UYU", symbol: "$U", name: "Uruguayan Peso" }, cities: ["Montevideo", "Salto", "Ciudad de la Costa", "Paysandú", "Las Piedras", "Rivera", "Maldonado", "Tacuarembó", "Melo", "Mercedes"], states: [
    { name: "Montevideo",  code: "MO", cities: ["Montevideo"] },
    { name: "Salto",       code: "SA", cities: ["Salto"] },
    { name: "Canelones",   code: "CA", cities: ["Ciudad de la Costa", "Las Piedras"] },
    { name: "Paysandú",    code: "PA", cities: ["Paysandú"] },
    { name: "Rivera",      code: "RV", cities: ["Rivera"] },
    { name: "Maldonado",   code: "MA", cities: ["Maldonado"] },
    { name: "Tacuarembó",  code: "TA", cities: ["Tacuarembó"] },
    { name: "Cerro Largo", code: "CL", cities: ["Melo"] },
    { name: "Soriano",     code: "SO", cities: ["Mercedes"] },
  ] },
  { name: "Venezuela", code: "VE", currency: { code: "VES", symbol: "Bs.", name: "Venezuelan Bolívar" }, cities: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana", "San Cristóbal", "Maturín", "Cumana", "Barinas"], states: [
    { name: "Capital District", code: "A", cities: ["Caracas"] },
    { name: "Zulia",            code: "V", cities: ["Maracaibo"] },
    { name: "Carabobo",         code: "G", cities: ["Valencia"] },
    { name: "Lara",             code: "K", cities: ["Barquisimeto"] },
    { name: "Aragua",           code: "D", cities: ["Maracay"] },
    { name: "Bolívar",          code: "F", cities: ["Ciudad Guayana"] },
    { name: "Táchira",          code: "S", cities: ["San Cristóbal"] },
    { name: "Monagas",          code: "N", cities: ["Maturín"] },
    { name: "Sucre",            code: "R", cities: ["Cumana"] },
    { name: "Barinas",          code: "E", cities: ["Barinas"] },
  ] },
  { name: "Vietnam", code: "VN", currency: { code: "VND", symbol: "₫", name: "Vietnamese Dong" }, cities: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Can Tho", "Hai Phong", "Bien Hoa", "Hue", "Nha Trang", "Buon Ma Thuot", "Quy Nhon"], states: [
    { name: "Ho Chi Minh City",   code: "SG", cities: ["Ho Chi Minh City"] },
    { name: "Hanoi",              code: "HN", cities: ["Hanoi"] },
    { name: "Da Nang",            code: "DN", cities: ["Da Nang"] },
    { name: "Can Tho",            code: "CT", cities: ["Can Tho"] },
    { name: "Hai Phong",          code: "HP", cities: ["Hai Phong"] },
    { name: "Đồng Nai",           code: "39", cities: ["Bien Hoa"] },
    { name: "Thừa Thiên-Huế",     code: "26", cities: ["Hue"] },
    { name: "Khánh Hòa",          code: "34", cities: ["Nha Trang"] },
    { name: "Đắk Lắk",            code: "33", cities: ["Buon Ma Thuot"] },
    { name: "Bình Định",          code: "31", cities: ["Quy Nhon"] },
  ] },
];

export const USD = { code: "USD", symbol: "$", name: "US Dollar" };

export function getCurrencyForCountry(countryName: string) {
  return COUNTRIES.find(c => c.name === countryName)?.currency ?? USD;
}

/**
 * Returns the structured state/province list for a country, or [] if the
 * country has no meaningful top-level subdivision (in which case UIs should
 * disable / hide the State picker).
 */
export function getStatesForCountry(countryName: string): StateData[] {
  return COUNTRIES.find(c => c.name === countryName)?.states ?? [];
}

/**
 * Returns the cities for a country, optionally filtered by state. If `state`
 * is omitted (or the country has no state list), returns the country's flat
 * city list.
 */
export function getCitiesForCountry(countryName: string, stateName?: string): string[] {
  const country = COUNTRIES.find(c => c.name === countryName);
  if (!country) return [];
  if (stateName && country.states) {
    return country.states.find(s => s.name === stateName)?.cities ?? [];
  }
  return country.cities;
}
