import type { AssessmentDefinition, AssessmentPath, AssessmentTaskDefinition } from "./types";

const tasks = (path: AssessmentPath): AssessmentTaskDefinition[] => [
  { key: "conditional-transfer", title: "Explain a dependent update", instructions: "A transfer depends on identity verification; after verification, processing takes up to one business day. Explain the condition and timing without certainty about verification.", responseMode: path === "voice" ? "spoken_or_typed" : "typed", minimumNonSpaceCharacters: 40, coveredDimensions: ["clarity_structure", "action_accuracy"], facts: [{ id: "condition", description: "verification is required first", patterns: ["identity\\s+verification", "verification.*complete"] }, { id: "timing", description: "processing takes up to one business day", patterns: ["one\\s+business\\s+day", "up\\s+to\\s+1\\s+business\\s+day"] }], unsafePromises: [{ description: "a guaranteed same-day transfer", patterns: ["guarantee.*today", "transfer.*certain.*today", "will\\s+be\\s+complete\\s+today"] }], recommendationLessonIds: { clarity_structure: ["practice-advanced-clarity"], action_accuracy: ["practice-solutions-complex-cases"] } },
  { key: "booking-empathy", title: "Handle a disputed fee", instructions: "A customer says booking BK-731 moved from 18 to 21 July, and £30 was charged although an agent said a disruption waiver applied. Acknowledge the concern, preserve uncertainty, and state a check.", responseMode: path === "voice" ? "spoken_or_typed" : "typed", minimumNonSpaceCharacters: 45, coveredDimensions: ["empathy_tone", "clarification", "action_accuracy"], facts: [{ id: "booking", description: "booking BK-731 moved dates", patterns: ["BK[-\\s]?731", "18\\s+July", "21\\s+July"] }, { id: "fee", description: "the fee is £30", patterns: ["£?30"] }, { id: "check", description: "the waiver or booking will be checked", patterns: ["check", "verify", "review", "look\\s+into"] }], unsafePromises: [{ description: "a refund promised before review", patterns: ["guarantee.*refund", "refund.*(?:definitely|certainly|will\\s+be\\s+issued)"] }], recommendationLessonIds: { empathy_tone: ["practice-empathy-deescalation"], clarification: ["practice-probing-questions"], action_accuracy: ["practice-solutions-complex-cases"] } },
  { key: "invoice-probe", title: "Probe an ambiguous report", instructions: "A customer says the app is 'playing up' when opening invoices. Ask a focused question about the observable behaviour and scope.", responseMode: path === "voice" ? "spoken_or_typed" : "typed", minimumNonSpaceCharacters: 25, coveredDimensions: ["clarification", "empathy_tone"], facts: [{ id: "behaviour", description: "the question checks what the customer sees", patterns: ["sign[-\\s]?in", "logged\\s+out", "return(?:s|ed)?\\s+to", "what\\s+(?:do|does)\\s+you\\s+see"] }, { id: "scope", description: "the question checks invoice scope", patterns: ["any\\s+invoice", "all\\s+invoice", "one\\s+invoice", "particular\\s+invoice"] }], unsafePromises: [{ description: "an unverified technical diagnosis", patterns: ["it\\s+is\\s+(?:definitely\\s+)?a\\s+bug", "server\\s+error\\s+is\\s+the\\s+cause"] }], recommendationLessonIds: { clarification: ["practice-probing-questions"], empathy_tone: ["practice-empathy-deescalation"] } },
  { key: "crm-handoff", title: "Write the operational handoff", instructions: "Write a CRM handoff: Priya reports invoice 771 has a wrong tax address; identity is verified; there is no payment issue; it was sent to Billing as BI-903; update by Friday email.", responseMode: path === "voice" ? "spoken_or_typed" : "typed", minimumNonSpaceCharacters: 55, coveredDimensions: ["channel_execution", "clarity_structure", "action_accuracy"], facts: [{ id: "reference", description: "invoice 771 and case BI-903 are recorded", patterns: ["invoice\\s+771", "BI[-\\s]?903"] }, { id: "issue_scope", description: "the tax-address issue is separate from payment", patterns: ["tax\\s+address", "no\\s+payment\\s+issue", "payment.*(?:not|no).*issue"] }, { id: "next", description: "Billing owns the handoff and Friday email update", patterns: ["Billing", "Friday", "email"] }], unsafePromises: [{ description: "a completed correction stated before it occurs", patterns: ["tax\\s+address\\s+(?:is|was)\\s+fixed", "correction\\s+complete"] }], recommendationLessonIds: { channel_execution: [path === "voice" ? "practice-spontaneous-call-simulation" : "practice-written-chat-crm"], clarity_structure: ["practice-advanced-clarity"], action_accuracy: [path === "voice" ? "practice-solutions-complex-cases" : "practice-written-case-email"] } },
];

export const PRACTICE_ASSESSMENTS: Record<AssessmentPath, AssessmentDefinition> = {
  voice: { courseId: "support-communication-practice", path: "voice", title: "Practice developmental reassessment — voice practice", introduction: "Speak aloud and use the browser transcript, or type the exact response. The transcript is the evidence record; audio is never stored.", tasks: tasks("voice") },
  chat_email: { courseId: "support-communication-practice", path: "chat_email", title: "Practice developmental reassessment — chat and email", introduction: "Respond in writing as a customer chat or email, including the CRM handoff where requested. This is private developmental evidence.", tasks: tasks("chat_email") },
};