/**
 * schema/pipeline.ts — Job Pipeline Canvas, Outreach Messages & Run Tables
 *
 * ─── Tables ──────────────────────────────────────────────────────────────────
 *   job_pipelines      — Pipeline canvas configuration per job: stage order,
 *                        enabled agents, stage SLA config, and visual layout JSON.
 *   outreach_messages  — Personalised outreach messages generated by the
 *                        orchestrator's outreach agent; linked to a candidate and job.
 *   pipeline_runs      — Execution log for a full pipeline run: which agents
 *                        were triggered, per-stage status, and run metadata.
 *
 * ─── Used by ─────────────────────────────────────────────────────────────────
 *   routes/pipeline.ts        — Kanban board, run orchestration API
 *   lib/agents/orchestrator.ts — runPipeline() updates pipeline_runs
 */
import { pgTable, pgView, text, timestamp, boolean, jsonb, integer, index } from "drizzle-orm/pg-core";

export const jobPipelinesTable = pgTable("job_pipelines", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  jobId: text("job_id").notNull().unique(),
  tenantId: text("tenant_id").notNull().default("acme"),
  agents: jsonb("agents").notNull().default([]),
  agentConfig: jsonb("agent_config").notNull().default({}),
  /* Selected interview sub-types (e.g. ["cultural"], ["behavioral","technical"]).
   * Persisted from the Workflow Canvas so the Interview agent can constrain
   * which question categories run for this job. Empty array = use the
   * orchestrator's default ("general"). */
  interviewTypes: jsonb("interview_types").notNull().default([]),
  /* Recruiter-authored interview direction per job, keyed by interview type
   * (e.g. "behavioral") plus a "_default" bucket used by the pipeline control.
   * Each entry: { focusDirective?: string, customQuestions?: string[] }.
   * Consumed by generate-link (Workflow "Run Agents") and the pipeline
   * auto-interview (sendInterviewInviteFromReply → ensurePlan). */
  interviewDirection: jsonb("interview_direction").notNull().default({}),
  autoRun: boolean("auto_run").notNull().default(false),
  targetCandidates: integer("target_candidates").notNull().default(5),
  status: text("status").notNull().default("idle"),
  currentStage: text("current_stage"),
  lastRunAt: timestamp("last_run_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const outreachMessagesTable = pgTable("outreach_messages", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  jobId: text("job_id").notNull(),
  candidateId: text("candidate_id").notNull(),
  tenantId: text("tenant_id").notNull().default("acme"),
  subject: text("subject").notNull(),
  body: text("body").notNull(),
  status: text("status").notNull().default("queued"),
  tone: text("tone"),
  callToAction: text("call_to_action"),
  followUpSchedule: jsonb("follow_up_schedule").default([]),
  followUpsDispatched: jsonb("follow_ups_dispatched").default([]),
  estimatedOpenRate: text("estimated_open_rate"),
  sentAt: timestamp("sent_at"),
  openedAt: timestamp("opened_at"),
  repliedAt: timestamp("replied_at"),
  replySentiment: text("reply_sentiment"),
  interviewLink: text("interview_link"),
  // Approval gate (first cold outreach). status values now include
  // "pending_approval" (awaiting recruiter sign-off) and "rejected".
  approvedAt: timestamp("approved_at"),
  approvedBy: text("approved_by"),
  rejectedAt: timestamp("rejected_at"),
  rejectedReason: text("rejected_reason"),
  // Reason an SES dispatch failed (set when status="failed").
  failedReason: text("failed_reason"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const pipelineRunsTable = pgTable("pipeline_runs", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  jobId: text("job_id").notNull(),
  tenantId: text("tenant_id").notNull().default("acme"),
  triggeredBy: text("triggered_by").notNull().default("user"),
  /** WHICH authenticated user initiated the run (nullable — scheduler/system and
   *  historical rows are NULL). Distinct from the coarse `triggeredBy` label
   *  ("user"/"auto"/"orchestrator"/"scheduler"); this is the durable audit of
   *  who. Populated at insert from getAuthUserId (see routes/agents.ts). */
  triggeredByUserId: text("triggered_by_user_id"),
  status: text("status").notNull().default("running"),
  stages: jsonb("stages").notNull().default([]),
  startedAt: timestamp("started_at").notNull().defaultNow(),
  completedAt: timestamp("completed_at"),
  error: text("error"),
});

/**
 * pipeline_run_events — persisted event stream for pipeline_runs (the durable
 * counterpart to the in-memory orchestrator buffer). Mirrors agent_run_events
 * (schema/agent-runs.ts) column-for-column so the two feed the run_activity_events
 * union view cleanly. tenant_id + FORCE RLS; ordered per-run by `seq`. Writes are
 * best-effort/non-blocking (see lib/pipeline-runs/recorder.ts). See migration 0043
 * and docs/adr/0001-pipeline-run-events.md.
 */
export const pipelineRunEventsTable = pgTable("pipeline_run_events", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  tenantId: text("tenant_id").notNull(),
  /* FK → pipeline_runs(id) ON DELETE CASCADE (enforced in the migration). */
  runId: text("run_id").notNull(),
  /* Monotonic per-run ordering (UNIQUE(run_id, seq)). */
  seq: integer("seq").notNull(),
  /* run_started | step_started | step_completed | run_completed | run_failed |
     run_interrupted (free-text so the union view mixes freely with agent events). */
  type: text("type").notNull(),
  /* Agent id for step_* events (icp | sourcing | screening | …); null for run_*. */
  stepName: text("step_name"),
  message: text("message").notNull(),
  count: integer("count"),
  payload: jsonb("payload"),
  timestamp: timestamp("timestamp", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  runSeqIdx: index("pipeline_run_events_run_seq_idx").on(t.runId, t.seq),
  tenantIdx: index("pipeline_run_events_tenant_idx").on(t.tenantId),
}));

/**
 * run_activity_events — the ONLY sanctioned read surface for CROSS-RUN activity.
 * Normalizes agent_run_events + pipeline_run_events into one shape so consumers
 * never care which physical table an event came from. Defined in migration 0043
 * (security_invoker=true). Marked `.existing()` — drizzle reads it, never creates
 * it. If the two run models are ever unified this view is the seam (ADR 0001).
 */
export const runActivityEventsView = pgView("run_activity_events", {
  runId: text("run_id").notNull(),
  runType: text("run_type").notNull(),
  tenantId: text("tenant_id").notNull(),
  eventType: text("event_type").notNull(),
  stepName: text("step_name"),
  message: text("message").notNull(),
  count: integer("count"),
  payload: jsonb("payload"),
  timestamp: timestamp("timestamp", { withTimezone: true }).notNull(),
  seq: integer("seq").notNull(),
}).existing();

export type JobPipeline = typeof jobPipelinesTable.$inferSelect;
export type OutreachMessage = typeof outreachMessagesTable.$inferSelect;
export type PipelineRun = typeof pipelineRunsTable.$inferSelect;
export type PipelineRunEvent = typeof pipelineRunEventsTable.$inferSelect;
