/**
 * schema/staff_invite_tokens.ts — Staff Invite Token Table
 *
 * ─── Tables ──────────────────────────────────────────────────────────────────
 *   staff_invite_tokens   — One-time tokens that invite a new recruiter, admin,
 *                           or hiring manager to join a tenant. Generated by a
 *                           tenant admin; expires after 7 days; used to create
 *                           the user account on acceptance.
 *
 * ─── Used by ─────────────────────────────────────────────────────────────────
 *   routes/staff-invites.ts     — token generation, validation, acceptance
 *   routes/accept-team-invite.ts — frontend-facing acceptance endpoint
 */
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { userRoleEnum } from "./users";

export const staffInviteTokensTable = pgTable("staff_invite_tokens", {
  id:        text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  token:     text("token").notNull().unique(),
  email:     text("email").notNull(),
  name:      text("name").notNull(),
  role:      userRoleEnum("role").notNull(),
  tenantId:  text("tenant_id").notNull(),
  invitedBy: text("invited_by").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  usedAt:    timestamp("used_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export type StaffInviteToken = typeof staffInviteTokensTable.$inferSelect;
